### ISSUE TITLE
My experience as a new Erigon node hoster

### ISSUE THREAD

**Issue by qkum** [ledgerwatch/erigon#3121] opened 2021-12-14 00:33 UTC
Hello lovely people.

I recently started my own Erigon node and want to share some things I learned until now that can help others.

1) It seems the minimum RAM is 16 GB - if I use less on my virtual Ubuntu machine crashes.

2) Minimum CPU's is likely 4 cores. I have not tested with lower. 

3) I started testing with 8 cores instead of 4, I suspect it actually slowed down the initial sync by a lot. But I need my CPU cores for daily use so it will have to live with 4 for now.

4) If you reboot your Router, Disconnect VPN, or make a "snapshot" on your Virtual Machine while it is running. You will lose all the "peers" your node is connected to and you have to waste like 30-60 min to gain max peer count again. 

5) For me max "peer count" is (eth65=33, eth66=33) Some places they talk about 50 or 100 if I remember correctly, but for me, max is 33/33.

6) At times my VM will fall out of sync (the clock falls behind the real UNIX universal time) my VM loses its connected trusted "peers". but it updates its clock and fixes the problem automatically after some time but it will take 1-2 hours for it to be back at max trusted peers.

7) If you make a live "snapshot" while your VM is running you not just lose your trusted peers but the clock also goes out of sync btw.(the VM seems to freeze while savings the VM state - logically enough)

8) I have not found out how I can force the Ubuntu VM to update its clock so it will begin to build up trusted peers as fast as possible without having to wait maybe 30 min to update the clock itself. 
- Optimally the client would contain a script that detects the sudden loss of all trusted peers and automatically update the UNIX clock for the Linux machine. That would not be much-added code or computational load to the client and would help the whole network of archive nodes have less down-time as a whole. Meaning more up-time, meaning a more secure Ethereum blockchain.

9: I even experienced losing all trusted peers because I started downloading a big file on the pc hosting the Virtual Ubuntu Machine. My internet connection is Far Above the minimum 25 Mbps Download/25 Mbps upload. (35/43 as I write this).

10: I use an external USB 3, 4 TB HDD for running my Virtual Machine on. 

11: My setup worked decently the first 2-3 days and now it slowed down to like 25-50 GB a day of size increase of "du -hs /home/UserName/.local/share/erigon/chaindata" - the folder where the formated chain data is stored from what I understand. (I use this command to check progress)

12: I run Erigon Stable.

I hope my experience can help others.

---------------------------------------------------------------------------------------------------------------------------------------

*** Update: It was random bad luck that I lost all peers when I downloaded a file/files. It happens randomly several times a day.

*** After nearly 14 days the chaindata file is about 50% downloaded. So, it will take like 14 days more before my setup is done downloading the whole Ethereum Blockchain.

*** But It have not been running 24/7 I admit. Maybe on average 16 hours a day.

--- Slow and steady wins the race  🥇

**Comment by AskAlexSharov** [comment] 2021-12-14 07:51
Hi. Thank you. 
4. You can try external Sentry. It will hold connections during Erigon's reboot. About slowness of peers discovery - yes, we had couple complains about it, but didn't investigate yet.
5. As I know - it's expected Geth's behavior - to leave room for other peers to connect while limit good+new peers by MaxPeers parameter. You can search `defaultDialRatio` for more info. 
6. How we can reproduce "the clock falls behind the real UNIX universal time" problem?

**Comment by qkum** [comment] 2021-12-20 07:28
> Hi. Thank you. 4. You can try external Sentry. It will hold connections during Erigon's reboot. About slowness of peers discovery - yes, we had couple complains about it, but didn't investigate yet. 5. As I know - it's expected Geth's behavior - to leave room for other peers to connect while limit good+new peers by MaxPeers parameter. You can search `defaultDialRatio` for more info. 6. How we can reproduce "the clock falls behind the real UNIX universal time" problem?

6: It was likely because I created a snapshot of the Virtual Machine. It then freezes the VM screen, starts at 0 peers and begins to whine about the clock being 1.3 minutes behind - the same time it takes it to make a snapshot I realized later on. (I had so many problems the first week that made me super confused. So I did not have the mental clarity /focus to spot the cause at the time)

There is basically no manual on how to run this software.

Only pro jargon from what I can find in the wiki. (the technical details, not the everyday useful stuff for just running the node)

So, when you hit those errors, as you often do with open source, you are alone to figure it all out 🌵 

Not blaming, pointing fingers, or anything. Just reminding people if they have forgotten/overseen it.

I know all of you are working HARD every day - respect 💯

**Comment by qkum** [comment] 2021-12-20 07:32
Tip: Somehow you can turn the terminal in "read-only-mode" on ubuntu 18.04.

When that happens by bad luck. It seems a reboot fixed it, or maybe it was 2 😆 

It even gave warnings that made me think the Virtual Machine had corrupted or the HDD corrupted googleing the error message when I shut the Virtual Machine down trying to fix the "read-only" problem.

**Comment by mb-gvidon** [comment] 2021-12-30 11:26
BTW, @AskAlexSharov, 

It seems that I have issue with losing peers too.

I don't know whether it happens because of the mentioned clock thing, but the number of peers significantly decreased after the full sync. Moreover, I was even forced to restart the docker container, because I suddenly found out that my local erigon node was 19 hours behind the mainnet. It restored the number of peers back to 33 in 10 minutes, but then it fell down to 0-6, which actually bothers me a little bit. 

At the moment (couple of hours later after the issue above) my node seems to work +- stable (1 minute behind the mainnet), but actually I expected it working without any issues. 

Do you have any suggestions how can I increase the number of peers and my local node performance? Do I actually need it?  

I will be grateful for any comment.

**Comment by AskAlexSharov** [comment] 2021-12-30 13:05
I need re-check it. Now don't see peers drop on monitoring of my node. 
- "how can I increase the number of peers?" - there is --staticpeers flag. maybe you have some firewall/load-balancer/rate-limiter who block connection. hard to say, maybe in higher --verbosity can see some network-related errors.
- "and my local node performance?" - for blocks processing bottleneck is disk latency. 
- "Do I actually need it?" - depends on your use-case, usually default settings work well.

**Comment by mandrigin** [comment] 2022-07-16 09:09
closing this one, @mb-gvidon feel free to reopen if you still have questions/feedback

**Closed by mandrigin** 2022-07-16 09:09 UTC
