### ISSUE TITLE
ethstats: block number goes wild

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#1395] opened 2020-12-08 17:14 UTC
If you watch archivenode.io - node01 or node04 on ethstats you'll see that the current block number is completely unstable

https://ethstats.net/

The block number jumps wildly between about 10 blocks or so, it's like the ethstats client can't make up its mind what block number to report.

**Comment by mandrigin** [comment] 2020-12-08 17:18
That’s super weird. What are the logs for sync?

**Comment by MysticRyuujin** [comment] 2020-12-08 17:19
The logs for sync are perfectly normal/fine and just calling eth_blockNumber against the rpcdaemon works perfectly fine :man_shrugging:

**Comment by mandrigin** [comment] 2020-12-08 17:31
We only have newheads subscriptions and only if you enable websockets. If you run the node w/o websockets, it won’t gonna be using subscriptions because they aren’t working over regular http

**Comment by MysticRyuujin** [comment] 2020-12-08 18:06
:man_shrugging: you told me to open an issue if I saw incompatibility issues :smile:

**Comment by MysticRyuujin** [comment] 2020-12-08 19:07
WebSockets is enabled, yes!

**Comment by mandrigin** [comment] 2020-12-08 19:57
Try to disabling them to see if it stabilizes, that would help me to debug this one.

**Comment by MysticRyuujin** [comment] 2020-12-08 20:17
It does look like turning of websockets does fix it...I can't be 100% sure, I can run like this for a bit and watch it

**Comment by mandrigin** [comment] 2020-12-08 20:25
Thanks a lot!

**Comment by MysticRyuujin** [comment] 2020-12-08 22:37
It did not solve the problem. It might have helped or made it happen less? But I just witnessed it freak out again.

**Comment by mandrigin** [comment] 2020-12-09 17:44
hmm, no, unlikely... I'm wondering what could cause this behaviour, I can imagine if there were 2 instances of TG somehow and they had different block and then the rpc daemon jumps between them... I'll need to try to reproduce myself.

**Comment by AskAlexSharov** [comment] 2021-03-03 08:21
@MysticRyuujin this problem is still valid?

**Comment by MysticRyuujin** [comment] 2021-03-03 17:39
I have not ran ethstats against my node for a while now, I just fired it up, let me run it for a day or so and get back to you.

**Comment by MysticRyuujin** [comment] 2021-03-04 15:06
As far as I can tell this is fixed and I think this AND #835 can probably be closed...

**Comment by AndreaLanfranchi** [comment] 2021-06-09 17:03
Closing as feedback reports fixed

**Closed by AndreaLanfranchi** 2021-06-09 17:03 UTC
