### ISSUE TITLE
Erigon is making a lot of DNS queries

### ISSUE THREAD

**Issue by victorelec14** [ledgerwatch/erigon#9330] opened 2024-01-27 20:26 UTC
#### System information

Erigon version: v2.57.1 git_tag=v2.57.1-dirty 

OS & Version:  Docker

Commit hash: 9f1cd651f0b1b443b4bd96eaed84502c149fdca2

Erigon Command (with flags/config):

Consensus Layer:

Consensus Layer Command (with flags/config):
```
command:
      - --chain=mainnet
      - --http
      - --http.api=eth,net,web3,engine,admin,erigon,debug,trace,txpool #engine,eth,debug,net  # eth,erigon,web3,net,debug,trace,txpool
      - --private.api.addr=0.0.0.0:9090
      - --authrpc.jwtsecret=/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --snapshots
      - --torrent.download.rate=512mb
      - --torrent.upload.rate=500kb
      - --torrent.port=42068 # Public BitTorrent protocol listen
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --nat=any
      - --prune=htcr 
      - --verbosity=4
```

Chain/Network: Mainnet

#### Actual behaviour
Hi, i have been synchronizing the chain on Mainnet for a few days, now i started having problems with my DNS server, and I see that the requests Erigon is making are too many, even to Trackers domains that don't exist anymore.

Every day that Erigon is active, it generates around 460,000 DNS Queries. At the moment, it is making an average of 20 DNS Queries per second.

![image](https://github.com/ledgerwatch/erigon/assets/543450/35e705bb-6740-472e-8500-329dd0b00bcd)

![image](https://github.com/ledgerwatch/erigon/assets/543450/77277e9b-fc00-40fc-af63-9015742558fc)

9.rarbg.com  is a parked domain

![image](https://github.com/ledgerwatch/erigon/assets/543450/c64f8fef-5e51-4b9d-9712-a9434061a815)

Thanks !

**Comment by elee1766** [comment] 2024-01-29 02:54
it's an issue with the upstream torrent library, not erigon itself

https://github.com/anacrolix/torrent/issues/817

**Comment by yperbasis** [comment] 2024-05-09 09:53
Yeah, DNS on my Linux machine is broken even in the browser when the snapshot downloader is active, but it seems to be better on my MacBook.

**Comment by battlmonstr** [comment] 2024-06-10 10:02
duplicate of https://github.com/ledgerwatch/erigon/issues/5145

**Closed by battlmonstr** 2024-06-10 10:02 UTC
Labels: priority:high
