### ISSUE TITLE
Downloading block bodies: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#1622] opened 2021-03-29 07:54 UTC
#### System information

commit 0685250095a614a4167969300dad159d455f569b (HEAD -> master, origin/master, origin/HEAD)

Linux NUC 5.8.0-45-generic #51-Ubuntu SMP Fri Feb 19 13:24:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

#### Backtrace

````
INFO [03-29|01:05:55.233] [1/14 Headers] Imported new block headers count=2    elapsed=2.047ms     number=9929927 hash="526be2…f284f5"
INFO [03-29|01:06:03.500] [3/14 Bodies] Downloading block bodies   count=23892
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xe7e731]

goroutine 907634 [running]:
github.com/ledgerwatch/turbo-geth/eth/downloader.(*resultStore).AddFetch(0xc0099220a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/downloader/resultstore.go:83 +0x91
github.com/ledgerwatch/turbo-geth/eth/downloader.(*queue).reserveHeaders(0xc0004be870, 0xc00a956c30, 0x2, 0xc00829a5a0, 0xc000438ae0, 0xc00829a5d0, 0x0, 0xe74b1a, 0xc00a956d08)
        github.com/ledgerwatch/turbo-geth/eth/downloader/queue.go:516 +0x1bd
github.com/ledgerwatch/turbo-geth/eth/downloader.(*queue).ReserveBodies(0xc0004be870, 0xc00a956c30, 0x2, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/downloader/queue.go:468 +0xcb
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).fetchParts(0xc0003dc200, 0xc000437b60, 0xc00006fea0, 0xc00041c150, 0xc00006fe90, 0xc00006fef0, 0xc00006fee0, 0xc00006fed0, 0x0, 0x1427c28, ...)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1559 +0x1062
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).fetchBodies(0xc0003dc200, 0x972774, 0xc009764fb8, 0xe11b1a)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1367 +0x2c5
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).SpawnBodyDownloadStage.func4(0x0, 0x115ee80)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_stagedsync.go:134 +0x33
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync.func1(0xc0003dc200, 0xc00c8c2180, 0xc00874b020)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:695 +0x5b
created by github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:695 +0xaf
````

Also, before that TG started to skip stages. After Stage 1 it jumped straight to Stage 11:
````
INFO [03-28|23:31:07.507] [1/14 Headers] Imported new block headers count=1   elapsed=6.478ms   number=9930145 hash=
"11616f…db566b"
INFO [03-28|23:31:48.870] Looking for peers                        peercount=1 tried=11 static=0
INFO [03-28|23:31:59.148] Looking for peers                        peercount=1 tried=27 static=0
ERROR[03-28|23:32:05.415] Ethereum peer removal failed             peer=d16a87ff err="peer not registered"
WARN [03-28|23:32:05.421] Synchronisation failed, dropping peer    peer=d16a87ff749aba59e028c514ff15194d36c9f5a3773d
75afe804e84ced6eca90 err="action from bad peer ignored: header request timed out"
ERROR[03-28|23:32:05.421] Ethereum peer removal failed             peer=d16a87ff err="peer not registered"
INFO [03-28|23:32:09.574] Looking for peers                        peercount=1 tried=12 static=0
INFO [03-28|23:32:16.235] [1/14 Headers] Imported new block headers count=18  elapsed=4.062ms   number=9930155 hash=
"a315bf…3e706a"
INFO [03-28|23:32:16.418] [11/14 CallTraces] disabled. Work In Progress 
INFO [03-28|23:32:16.425] [13/14 TxPool] Read canonical hashes     hashes=0
INFO [03-28|23:32:16.425] [13/14 TxPool] Transaction stats         pending=25 queued=644
INFO [03-28|23:32:16.426] [14/14 Finish] Update current block for the RPC API to=9906035
INFO [03-28|23:32:16.427] Memory                                   alloc=208.98MiB  sys=8.52GiB
INFO [03-28|23:32:16.427] Timings                                  Headers=761.211061ms BlockHashes="167.318µs" Bodi
es=1.90786ms  Senders="36.25µs" Execution="18.84µs"         HashState="17.081µs"       IntermediateHashes="15.057µs"
      AccountHistoryIndex="31.307µs"      StorageHistoryIndex="20.976µs"      LogIndex="20.862µs"       TxLookup=1.7
````

I ran TG with Silkworm execution by calling:
````
build/bin/tg --ropsten --silkworm /home/andrew/silkworm/build/tg_api/libsilkworm_tg_api.so
````

I'm attaching the full log.
[out.log.gz](https://github.com/ledgerwatch/turbo-geth/files/6220222/out.log.gz)

**Comment by AndreaLanfranchi** [comment] 2021-04-08 13:01
Happened to me as well but on mainnet and **without** silkworm integration.
Was not able to reproduce.

![image](https://user-images.githubusercontent.com/15280851/114031081-4de22e00-987b-11eb-8585-172169c33ee1.png)

**Comment by AndreaLanfranchi** [comment] 2021-04-08 13:03
More over "short" commit cycles (11-14) are frequent

```
ermediateHashes=132.2404ms AccountHistoryIndex=43.1546ms  StorageHistoryIndex=54.3767ms  LogIndex=34.0478ms  TxLookup=104.1406ms TxPool=26.7443ms Finish="48.9µs"
INFO [04-08|14:48:54.498] Commit cycle                             in=591.2123ms
INFO [04-08|14:49:07.861] [1/14 Headers] Imported new block headers count=1 elapsed=2.119ms   number=12199222 hash="6e9d76…5ff705"
INFO [04-08|14:49:07.959] [11/14 CallTraces] disabled. Work In Progress
INFO [04-08|14:49:07.981] [13/14 TxPool] Read canonical hashes     hashes=0
INFO [04-08|14:49:07.982] [13/14 TxPool] Transaction stats         pending=4097 queued=1021
INFO [04-08|14:49:07.983] [14/14 Finish] Update current block for the RPC API to=12199222
INFO [04-08|14:49:07.983] Memory                                   alloc=339.06MiB sys=567.24MiB
INFO [04-08|14:49:07.983] Timings                                  Headers=317.7417ms BlockHashes="552.3µs" Bodies="151µs"     Senders=0s        Execution=0s         HashState=0s         IntermediateHashes=0s
        AccountHistoryIndex=0s         StorageHistoryIndex=0s         LogIndex=0s         TxLookup=0s         TxPool=23.7355ms Finish=0s
INFO [04-08|14:49:07.984] Commit cycle                             in=1.0017ms
INFO [04-08|14:49:08.326] [11/14 CallTraces] disabled. Work In Progress
INFO [04-08|14:49:08.349] [13/14 TxPool] Read canonical hashes     hashes=0
INFO [04-08|14:49:08.351] [13/14 TxPool] Transaction stats         pending=4097 queued=1023
INFO [04-08|14:49:08.351] [14/14 Finish] Update current block for the RPC API to=12199222
INFO [04-08|14:49:08.351] Memory                                   alloc=348.52MiB sys=567.24MiB
INFO [04-08|14:49:08.351] Timings                                  Headers=213.3136ms BlockHashes="661.5µs" Bodies="444.3µs"   Senders=0s        Execution=0s         HashState=0s         IntermediateHashes=0s
        AccountHistoryIndex=0s         StorageHistoryIndex=0s         LogIndex=0s         TxLookup="51.5µs"   TxPool=24.7398ms Finish=0s
INFO [04-08|14:49:08.353] Commit cycle                             in=2.0352ms
INFO [04-08|14:49:08.809] [11/14 CallTraces] disabled. Work In Progress
INFO [04-08|14:49:08.834] [13/14 TxPool] Read canonical hashes     hashes=0
INFO [04-08|14:49:08.835] [13/14 TxPool] Transaction stats         pending=4096 queued=1024
INFO [04-08|14:49:08.835] [14/14 Finish] Update current block for the RPC API to=12199222
INFO [04-08|14:49:08.835] Memory                                   alloc=357.73MiB sys=567.24MiB
INFO [04-08|14:49:08.835] Timings                                  Headers=327.2158ms BlockHashes=0s        Bodies=1.0372ms    Senders=0s        Execution=0s         HashState=0s         IntermediateHashes=0s
        AccountHistoryIndex=0s         StorageHistoryIndex="55.5µs"   LogIndex=0s         TxLookup=0s         TxPool=25.5904ms Finish=0s
INFO [04-08|14:49:08.837] Commit cycle                             in="999.3µs"
```

**Comment by AskAlexSharov** [comment] 2021-04-08 14:35
Problem with tx_pool fixed today. In master now. 
Panic in downloader - not clear how to fix yet.

**Comment by yperbasis** [comment] 2021-04-15 09:47
I observer a similar problem with the mainnet (and silkworm execution). I think it happens after unwinding.
```
commit 6b4193a462a9d4ff58c9b2ebd7b2d36cf3456e93 (HEAD -> master, origin/master, origin/HEAD)
```

```
INFO [04-15|09:36:41.567] [13/14 TxPool] Transaction stats         pending=4082 queued=1018
INFO [04-15|09:36:41.567] Commit cycle 
INFO [04-15|09:36:41.762] Unwinding...                             stage=Bodies
INFO [04-15|09:36:41.805] Unwinding...                             stage=BlockHashes
INFO [04-15|09:36:41.851] Unwinding...                             stage=Headers
INFO [04-15|09:36:42.343] [3/14 Bodies] Downloading block bodies   count=2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xe80071]

goroutine 630043 [running]:
github.com/ledgerwatch/turbo-geth/eth/downloader.(*resultStore).AddFetch(0xc01365e370, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/downloader/resultstore.go:83 +0x91
github.com/ledgerwatch/turbo-geth/eth/downloader.(*queue).reserveHeaders(0xc00040a7e0, 0xc00f62d3b0, 0x2, 0xc0002684b0, 0xc000134258, 0xc0002684e0, 0x0, 0xe764ba, 0xc00f62d488)
        github.com/ledgerwatch/turbo-geth/eth/downloader/queue.go:513 +0x1bd
github.com/ledgerwatch/turbo-geth/eth/downloader.(*queue).ReserveBodies(0xc00040a7e0, 0xc00f62d3b0, 0x2, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/downloader/queue.go:465 +0xc8
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).fetchParts(0xc00000c1e0, 0xc0017620c0, 0xc00cc97ea0, 0xc00004c2a0, 0xc00cc97e90, 0xc00cc97ef0, 0xc00cc97ee0, 0xc00cc97ed0, 0x0, 0x166e768, ...)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1336 +0x1062
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).fetchBodies(0xc00000c1e0, 0xbad395, 0x1, 0xc000d5df80)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:1170 +0x2c5
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).SpawnBodyDownloadStage.func4(0x2, 0x100)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_stagedsync.go:131 +0x33
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync.func1(0xc00000c1e0, 0xc00b487980, 0xc015164a08)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:592 +0x5b
created by github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:592 +0xaf
```

**Comment by AskAlexSharov** [comment] 2021-05-22 04:27
Closing this, because - we released --downloader.v2 and it doesn't use Downloader

**Closed by AskAlexSharov** 2021-05-22 04:27 UTC
