### ISSUE TITLE
Erigon does not build with Go1.21

### ISSUE THREAD

**Issue by lmittmann** [ledgerwatch/erigon#8107] opened 2023-08-31 15:29 UTC
```
$ go version
go version go1.21.0 linux/amd64
$ make erigon 
Building erigon
# github.com/quic-go/quic-go/internal/qtls
/root/go/pkg/mod/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
make: *** [Makefile:97: erigon.cmd] Error 1
```

**Comment by AskAlexSharov** [comment] 2023-09-01 00:15
Duplicate of https://github.com/ledgerwatch/erigon/issues/7984

**Closed by AskAlexSharov** 2023-09-01 00:15 UTC
