### ISSUE TITLE
crash on mdbx put

### ISSUE THREAD

**Issue by sudeepdino008** [ledgerwatch/erigon#10756] opened 2024-06-14 15:46 UTC
#### System information

Erigon version: `./erigon --version`
started out at 2.59.2, now updated to 2.60.1

OS & Version: Windows/Linux/OSX

Commit hash: 

Erigon Command (with flags/config):
`erigon --datadir "/mnt/data/ethereum/erigon_full" --chain mainnet --port=30303 --http.port=8545 --authrpc.port=8551 --http.corsdomain "*" --torrent.port=42069 --private.api.addr=127.0.0.1:9090 --http --ws --http.api=eth,debug,net,trace,web3,erigon --authrpc.jwtsecret=/mnt/data/ethereum/jwt.hex --internalcl`

Consensus Layer:
caplin

Chain/Network: 
mainnet

#### Expected behaviour
erigon syncs

#### Actual behaviour

got a crash:
[internal_cl_log.log](https://github.com/user-attachments/files/15840521/internal_cl_log.log)

For more details, look at: https://discord.com/channels/687972960811745322/1250724159655514112/1250728027101462589

**Comment by sudeepdino008** [comment] 2024-06-14 15:46
asked user if the storage space is exhausted (since segmentation fault on mdbx put).

**Comment by dvovk** [comment] 2024-06-18 10:23
User reported that he has enough space ("I have 10T/25T space available")

**Comment by AskAlexSharov** [comment] 2024-06-20 07:43
duplicate of https://github.com/ledgerwatch/erigon/issues/10814#issuecomment-2179932294

**Comment by yperbasis** [comment] 2024-06-28 09:13
Closing as duplicate of #10814

**Closed** 2024-06-28 09:13 UTC
