### ISSUE TITLE
data races running TestMiningBenchmark

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#8704] opened 2023-11-11 15:35 UTC
```
==================
WARNING: DATA RACE
Write at 0x00c0000363e8 by goroutine 194:
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).loop()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:609 +0xb12
  github.com/ledgerwatch/erigon/p2p/discover.ListenV4.func2()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:184 +0x33

Previous read at 0x00c0000363e8 by goroutine 200:
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).ensureBond()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:798 +0x1ba
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).findnode()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:365 +0x67
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).newLookup.func1()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:351 +0x165
  github.com/ledgerwatch/erigon/p2p/discover.(*lookup).query()
      github.com/ledgerwatch/erigon/p2p/discover/lookup.go:157 +0x16b
  github.com/ledgerwatch/erigon/p2p/discover.(*lookup).startQueries.func1()
      github.com/ledgerwatch/erigon/p2p/discover/lookup.go:128 +0x4f

Goroutine 194 (running) created at:
  github.com/ledgerwatch/erigon/p2p/discover.ListenV4()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:184 +0xa6a
  github.com/ledgerwatch/erigon/p2p/discover.newUDPTestContext()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp_test.go:90 +0x786
  github.com/ledgerwatch/erigon/p2p/discover.TestUDPv4_Lookup()
      github.com/ledgerwatch/erigon/p2p/discover/v4_lookup_test.go:45 +0xc4
  testing.tRunner()
      testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      testing/testing.go:1648 +0x44

Goroutine 200 (running) created at:
  github.com/ledgerwatch/erigon/p2p/discover.(*lookup).startQueries()
      github.com/ledgerwatch/erigon/p2p/discover/lookup.go:128 +0x524
  github.com/ledgerwatch/erigon/p2p/discover.(*lookup).advance()
      github.com/ledgerwatch/erigon/p2p/discover/lookup.go:72 +0x3e
  github.com/ledgerwatch/erigon/p2p/discover.(*lookup).run()
      github.com/ledgerwatch/erigon/p2p/discover/lookup.go:64 +0x2e
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).LookupPubkey()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:319 +0x1ec
  github.com/ledgerwatch/erigon/p2p/discover.TestUDPv4_Lookup()
      github.com/ledgerwatch/erigon/p2p/discover/v4_lookup_test.go:61 +0x584
  testing.tRunner()
      testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      testing/testing.go:1648 +0x44
==================
--- FAIL: TestUDPv4_LookupIteratorClose (0.06s)
```

```
==================
WARNING: DATA RACE
Write at 0x00c003b8e268 by goroutine 380:
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).loop()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:609 +0xb12
  github.com/ledgerwatch/erigon/p2p/discover.ListenV4.func2()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:184 +0x33

Previous read at 0x00c003b8e268 by goroutine 6205:
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).ping()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:271 +0x1e9
  github.com/ledgerwatch/erigon/p2p/discover.(*Table).doRevalidate()
      github.com/ledgerwatch/erigon/p2p/discover/table.go:404 +0x169
  github.com/ledgerwatch/erigon/p2p/discover.(*Table).loop.func10()
      github.com/ledgerwatch/erigon/p2p/discover/table.go:291 +0x44

Goroutine 380 (running) created at:
  github.com/ledgerwatch/erigon/p2p/discover.ListenV4()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:184 +0xa6a
  github.com/ledgerwatch/erigon/p2p.(*Server).setupDiscovery()
      github.com/ledgerwatch/erigon/p2p/server.go:661 +0xb66
  github.com/ledgerwatch/erigon/p2p.(*Server).Start()
      github.com/ledgerwatch/erigon/p2p/server.go:536 +0x9d5
  github.com/ledgerwatch/erigon/p2p/sentry.(*GrpcServer).SetStatus()
      github.com/ledgerwatch/erigon/p2p/sentry/sentry_grpc_server.go:1011 +0xd7e
  github.com/ledgerwatch/erigon-lib/direct.(*SentryClientDirect).SetStatus()
      github.com/ledgerwatch/erigon-lib@v1.0.0/direct/sentry_client.go:230 +0x62
  github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client.sentryReconnectAndPumpStreamLoop[go.shape.*uint8]()
      github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client/sentry_multi_client.go:156 +0x3f9
  github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client.(*MultiClient).RecvMessageLoop()
      github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client/sentry_multi_client.go:113 +0x3f6
  github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client.(*MultiClient).StartStreamLoops.func1()
      github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client/sentry_multi_client.go:60 +0x6e

Goroutine 6205 (running) created at:
  github.com/ledgerwatch/erigon/p2p/discover.(*Table).loop()
      github.com/ledgerwatch/erigon/p2p/discover/table.go:291 +0x72a
  github.com/ledgerwatch/erigon/p2p/discover.ListenV4.func1()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:181 +0x33
==================
==================
WARNING: DATA RACE
Write at 0x00c0002b01e8 by goroutine 380:
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).loop()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:609 +0xb12
  github.com/ledgerwatch/erigon/p2p/discover.ListenV4.func2()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:184 +0x33

Previous read at 0x00c0002b01e8 by goroutine 6205:
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).ensureBond()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:798 +0x1ba
  github.com/ledgerwatch/erigon/p2p/discover.(*UDPv4).RequestENR()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:411 +0x208
  github.com/ledgerwatch/erigon/p2p/discover.(*Table).doRevalidate()
      github.com/ledgerwatch/erigon/p2p/discover/table.go:409 +0x201
  github.com/ledgerwatch/erigon/p2p/discover.(*Table).loop.func10()
      github.com/ledgerwatch/erigon/p2p/discover/table.go:291 +0x44

Goroutine 380 (running) created at:
  github.com/ledgerwatch/erigon/p2p/discover.ListenV4()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:184 +0xa6a
  github.com/ledgerwatch/erigon/p2p.(*Server).setupDiscovery()
      github.com/ledgerwatch/erigon/p2p/server.go:661 +0xb66
  github.com/ledgerwatch/erigon/p2p.(*Server).Start()
      github.com/ledgerwatch/erigon/p2p/server.go:536 +0x9d5
  github.com/ledgerwatch/erigon/p2p/sentry.(*GrpcServer).SetStatus()
      github.com/ledgerwatch/erigon/p2p/sentry/sentry_grpc_server.go:1011 +0xd7e
  github.com/ledgerwatch/erigon-lib/direct.(*SentryClientDirect).SetStatus()
      github.com/ledgerwatch/erigon-lib@v1.0.0/direct/sentry_client.go:230 +0x62
  github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client.sentryReconnectAndPumpStreamLoop[go.shape.*uint8]()
      github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client/sentry_multi_client.go:156 +0x3f9
  github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client.(*MultiClient).RecvMessageLoop()
      github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client/sentry_multi_client.go:113 +0x3f6
  github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client.(*MultiClient).StartStreamLoops.func1()
      github.com/ledgerwatch/erigon/p2p/sentry/sentry_multi_client/sentry_multi_client.go:60 +0x6e

Goroutine 6205 (running) created at:
  github.com/ledgerwatch/erigon/p2p/discover.(*Table).loop()
      github.com/ledgerwatch/erigon/p2p/discover/table.go:291 +0x72a
  github.com/ledgerwatch/erigon/p2p/discover.ListenV4.func1()
      github.com/ledgerwatch/erigon/p2p/discover/v4_udp.go:181 +0x33
==================
INFO[11-11|15:19:17.602] [6/6 MiningFinish] block ready for seal  block_num=9 transactions=350 gas_used=7350000 gas_limit=20000000 difficulty=2
INFO[11-11|15:19:17.602] Waiting for slot to sign and propagate   number=9 hash=0x2d558c0 delay=397.665ms TxCount=350 Signer=0x71562b71999873DB5b286dF957af199Ec94617F7
INFO[11-11|15:19:18.001] Sealed in-turn                           number=9 delay=397.665504ms headerDifficulty=2 signer=0x71562b71999873DB5b286dF957af199Ec94617F7
INFO[11-11|15:19:18.003] [2/15 Headers] Processed                 highest inserted=9 age=0
INFO[11-11|15:19:18.141] Committed State                          gas reached=0 gasTarget=0
INFO[11-11|15:19:18.146] [7/15 Execution] Completed on            block=9
INFO[11-11|15:19:18.176] RPC Daemon notified of new headers       from=8 to=9 hash=0xe1cd9eb064d66ab146a9c880ff74b62139ea9af8f59e005f48de69ae4f1ee276 header sending=31.43µs log sending=750ns
INFO[11-11|15:19:18.176] Timings (slower than 50ms)               Headers=639ms Execution=98ms
INFO[11-11|15:19:18.178] [2/15 Headers] Waiting for headers...    from=9
INFO[11-11|15:19:18.180] [1/6 MiningCreateBlock] Start mine       block=10 baseFee=<nil> gasLimit=20000000


Time to execute 5000 txs: 14.902032828s
--- FAIL: TestMiningBenchmark (15.78s)
```

**Comment by battlmonstr** [comment] 2024-04-12 09:06
I'm able to reproduce some data races by running TestMiningBenchmark with a race detector:

```
CGO_CFLAGS="-D__BLST_PORTABLE__" go test -tags integration -run '^\QTestMiningBenchmark\E$' -race -v -count=1 ./tests/bor/...
```

But for me it is showing different issues:

```
WARNING: DATA RACE
Read at 0x00c000568068 by goroutine 17:
  github.com/ledgerwatch/erigon/p2p/sentry.(*GrpcServer).NodeInfo()
      /Users/daniel/Projects/erigon/erigon/p2p/sentry/sentry_grpc_server.go:1255 +0x38
WARNING: DATA RACE
Read at 0x00c001aca0e8 by goroutine 332:
  github.com/ledgerwatch/erigon/turbo/stages/headerdownload.(*HeaderDownload).InsertHeader()
      /Users/daniel/Projects/erigon/erigon/turbo/stages/headerdownload/header_algos.go:594 +0x17c8
```

CC @mh0lt , @taratorio

**Comment by battlmonstr** [comment] 2024-04-12 10:21
I've fixed some issues in https://github.com/ledgerwatch/erigon/pull/9926
It passes fine on Linux, but fails on macOS with:

> fatal error: too many address space collisions for -race mode

It seems that it is a too big of a test for the race detector to deal with.

**Comment by battlmonstr** [comment] 2024-04-12 12:01
Can't reproduce the failure of TestUDPv4_LookupIteratorClose, and the code at v4_udp.go:609 has changed since.

**Comment by battlmonstr** [comment] 2024-04-15 07:47
fixed by https://github.com/ledgerwatch/erigon/commit/fcad3a0328498d78e0924a411a0bdc3fd221cc81

**Closed by battlmonstr** 2024-04-15 07:47 UTC
Labels: priority:medium
