### ISSUE TITLE
Sync stuck during BSC blockchain pause

### ISSUE THREAD

**Issue by immibis** [ledgerwatch/erigon#5652] opened 2022-10-07 03:46 UTC
#### System information

Erigon version: erigon version 2022.09.3-stable-32bd69e5  
OS & Version: Linux 5.15.41-gentoo  
Commit hash : 32bd69e5316050005e34448ec6b0165f97173d50

#### Expected behaviour

Even though the network is currently not producing blocks, Erigon is still able to sync up to the last block or some point before.

#### Actual behaviour

After restart during syncing, Erigon does not continue syncing and appears to be waiting for the next block. The last sync-related log message is:
```
[2/16 Headers] Waiting for headers... from=21962149
```

However, the blockchain is stuck at block 2196214**7** until further notice according to [BSCScan](https://bscscan.com/)

Log sample when starting up in the stuck state:
```
INFO[10-07|05:37:33.429] Reading JWT secret                       path=/mnt/blockchain/bsc/erigon-data/jwt.hex
INFO[10-07|05:37:33.429] HTTP endpoint opened for Engine API      url=localhost:8552 ws=true ws.compression=true
INFO[10-07|05:37:33.429] HTTP endpoint opened                     url=localhost:8546 ws=false ws.compression=true grpc=false
INFO[10-07|05:37:33.434] Started P2P networking                   version=66 self=enode://<censored> name=erigon/v2022.09.3-stable-32bd69e5/linux-amd64/go1.18.2
INFO[10-07|05:37:33.441] [1/16 Snapshots] Fetching torrent files metadata 
INFO[10-07|05:37:33.443] [txpool] Started 
INFO[10-07|05:37:35.805] [Snapshots] Stat                         blocks=20000k indices=20000k alloc=2.5GB sys=2.7GB
INFO[10-07|05:37:35.805] [2/16 Headers] Waiting for headers...    from=21962149
INFO[10-07|05:38:33.430] [txpool] stat                            block=21962149 pending=1 baseFee=0 queued=209 alloc=2.7GB sys=2.9GB
INFO[10-07|05:39:15.806] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=21963685 skelMax=22258405 resp=28 respMin=21962149 respMax=21962149 dups=1
INFO[10-07|05:39:15.806] [Downloader] Queue sizes                 anchors=0 links=0 persisted=65536
INFO[10-07|05:39:33.147] [p2p] GoodPeers                          eth66=23
INFO[10-07|05:39:33.429] [txpool] stat                            block=21962149 pending=1 baseFee=0 queued=209 alloc=2.9GB sys=3.1GB
INFO[10-07|05:39:35.808] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=21963685 skelMax=22258405 resp=29 respMin=21962149 respMax=21962149 dups=1
INFO[10-07|05:39:35.808] [Downloader] Queue sizes                 anchors=0 links=0 persisted=65536
INFO[10-07|05:39:55.806] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=18 skelMin=21963685 skelMax=22258405 resp=36 respMin=0 respMax=21962149 dups=3
INFO[10-07|05:39:55.806] [Downloader] Queue sizes                 anchors=0 links=0 persisted=65536
```

Log sample after block creation resumed:

```
INFO[10-07|07:30:15.806] [Downloader] Queue sizes                 anchors=0 links=0 persisted=65536
INFO[10-07|07:30:33.429] [txpool] stat                            block=21962149 pending=1 baseFee=0 queued=209 alloc=2.6GB sys=3.1GB
INFO[10-07|07:30:35.806] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=21963685 skelMax=22258405 resp=35 respMin=0 respMax=0 dups=0
INFO[10-07|07:30:35.806] [Downloader] Queue sizes                 anchors=0 links=0 persisted=65536
INFO[10-07|07:30:55.805] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=21963685 skelMax=22258405 resp=31 respMin=0 respMax=0 dups=0
INFO[10-07|07:30:55.806] [Downloader] Queue sizes                 anchors=0 links=0 persisted=65536
INFO[10-07|07:31:15.460] [2/16 Headers] Processed                 highest inserted=21962150 age=5s
INFO[10-07|07:31:15.460] [2/16 Headers] DONE                      in=1h53m39.654848836s
INFO[10-07|07:31:15.462] [5/16 Bodies] Processing bodies...       from=20118268 to=21962150
INFO[10-07|07:31:33.147] [p2p] GoodPeers                          eth66=26
INFO[10-07|07:31:33.429] [txpool] stat                            block=21962149 pending=1 baseFee=0 queued=209 alloc=3.2GB sys=3.5GB
INFO[10-07|07:31:35.475] [5/16 Bodies] Wrote block bodies         block_num=20118268 delivery/sec=5.8MB wasted/sec=207.9KB alloc=3.2GB sys=3.6GB
INFO[10-07|07:31:55.462] [5/16 Bodies] Wrote block bodies         block_num=20118268 delivery/sec=8.1MB wasted/sec=1.2MB alloc=3.0GB sys=4.2GB
INFO[10-07|07:32:15.463] [5/16 Bodies] Wrote block bodies         block_num=20118268 delivery/sec=7.8MB wasted/sec=3.5MB alloc=4.2GB sys=4.5GB
INFO[10-07|07:32:33.430] [txpool] stat                            block=21962149 pending=1 baseFee=0 queued=209 alloc=4.7GB sys=5.0GB
INFO[10-07|07:32:35.463] [5/16 Bodies] Wrote block bodies         block_num=20118316 delivery/sec=3.1MB wasted/sec=1.5MB alloc=4.7GB sys=5.0GB
INFO[10-07|07:32:55.463] [5/16 Bodies] Wrote block bodies         block_num=20118362 delivery/sec=2.1MB wasted/sec=739.7KB alloc=5.1GB sys=5.4GB
INFO[10-07|07:33:15.464] [5/16 Bodies] Wrote block bodies         block_num=20118362 delivery/sec=3.0MB wasted/sec=2.0MB alloc=3.3GB sys=5.7GB
```

#### Steps to reproduce the behaviour

* Start syncing BSC. Run to stage 5/16 "Writing block headers"
* Hack BSC so that all validators stop creating blocks: https://twitter.com/BNBCHAIN/status/1578148078636650496
* Observe that Erigon continues writing block headers.
* Restart Erigon.
* Observe that Erigon does not sync.

Probably difficult to reproduce after block creation resumes, though it may be possible on a local testnet.

Command line:
```
erigon --chain=bsc --datadir=erigon-data --torrent.port=43070 --authrpc.port=8552 --http.port=8546 --port=30304 --private.api.addr=127.0.0.1:9091
```

#### Backtrace

n/a

**Comment by billyadelphia** [comment] 2022-10-07 06:14
Erigon need to implement this hardfork https://github.com/bnb-chain/bsc/releases/tag/v1.1.15

**Comment by billyadelphia** [comment] 2022-10-07 06:55
Using devel branch might solve the issue, trying it now https://github.com/ledgerwatch/erigon/commit/7144b2664ceba77bb0720f49c704f781d67c4942

**Comment by binhgo** [comment] 2022-10-07 10:24
is there any update on this? thanks

**Comment by AdminAnticaptcha** [comment] 2022-10-07 10:34
Latest release [2.27.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.27.0) fixes this one, already syncing.
https://github.com/ledgerwatch/erigon/releases

**Comment by immibis** [comment] 2022-10-07 11:20
> Erigon need to implement this hardfork https://github.com/bnb-chain/bsc/releases/tag/v1.1.15

I'm not sure the hardfork is relevant since the sync didn't get up to the hardfork block yet. The bug seems to be that sync doesn't start until a block is produced.

**Comment by PolarSyncZ** [comment] 2022-10-15 20:30
@immibis  You need ot upgrade to 2.28.0 and it will resolve the issue. See https://github.com/ledgerwatch/erigon/issues/5703. The issue is slightly different but the resolution is the same if the upgrade does not work the first time.

**Comment by revitteth** [comment] 2022-10-20 14:42
Should be fixed - let's reopen if not. :)

**Closed by revitteth** 2022-10-20 14:42 UTC
