### ISSUE TITLE
2022.06.6-alpha does not sync: err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"

### ISSUE THREAD

**Issue by c0deright** [ledgerwatch/erigon#4566] opened 2022-06-28 18:52 UTC
#### System information

Erigon version: erigon version 2022.06.6-alpha-77240899
git_commit=7724089985bf9cb8bb7d1bde92892256a6af859f

OS & Version: Ubuntu 20.04 LTS

#### Expected behaviour

Erigon does sync after downloading the snapshot

#### Actual behaviour

Erigon does loop an error and does nothing after torrent download.

#### Steps to reproduce the behaviour

Start erigon as follows:

`erigon --datadir /data/erigon --ethash.dagdir /data/.ethash-erigon --port 30307 --http --http.addr 0.0.0.0 --http.port 8549 --http.api "debug,eth,net,web3,erigon" --http.vhosts='*' --maxpeers 30 --verbosity 3 --private.api.addr '' --snap.stop --torrent.download.rate 100mb --prune hrtc --prune.h.older 2300000 --prune.r.older 2300000 --prune.t.older 2300000 --prune.c.older 2300000`

#### Log

````
[INFO] [06-28|15:56:22.930] Build info                               git_branch=HEAD git_tag=v2022.06.06 git_commit=7724089985bf9cb8bb7d1bde92892256a6af859f
[INFO] [06-28|15:56:22.930] Starting Erigon on Ethereum mainnet... 
[INFO] [06-28|15:56:22.932] Maximum peer count                       ETH=30 total=30
[INFO] [06-28|15:56:25.035] Set global gas cap                       cap=50000000
[INFO] [06-28|15:56:25.086] Opening Database                         label=chaindata path=/data/erigon/chaindata
[INFO] [06-28|15:56:25.093] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople:  7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
[INFO] [06-28|15:56:25.093] Initialising Ethereum protocol           network=1
[INFO] [06-28|15:56:25.093] Using snapshots                          on=true
[INFO] [06-28|15:56:25.094] Effective                                prune_flags="--prune.h.older=2300000 --prune.r.older=2300000 --prune.t.older=2300000 --prune.c.older=2300000" snapshot_flags="--snapshots=true --snap.stop=true"
[INFO] [06-28|15:56:26.909] Disk storage enabled for ethash DAGs     dir=/data/.ethash-erigon count=2
[INFO] [06-28|15:56:26.914] rpc filters: subscribing to Erigon events 
[INFO] [06-28|15:56:26.914] new subscription to newHeaders established 
[INFO] [06-28|15:56:26.914] new subscription to logs established 
[INFO] [06-28|15:56:26.915] New txs subscriber joined TraceRequests = false
[INFO] [06-28|15:56:26.916] HTTP endpoint opened                     url=0.0.0.0:8549 ws=false ws.compression=true grpc=false
[INFO] [06-28|15:56:26.921] Started P2P networking                   version=66 self=enode://936e2c027ac4dca72745386c19087600a832418449c7924a2a4a0f0885754cb05ec93f2306051eeb3cf3020e413d50ddd61a9fe1f7b61ec27cad3c2ae381abe4@127.0.0.1:30307 name=erigon/v2022.06.6-alpha-77240899/linux-amd64/go1.18.3
[INFO] [06-28|15:56:26.926] [Snapshots] Fetching torrent files metadata 
[INFO] [06-28|15:56:46.928] [Snapshots] download                     progress="64.54% 133.9GB/207.5GB" download=10.8MB/s upload=0B/s peers=4 connections=4 files=87 alloc=191.8MB sys=358.1MB
[INFO] [06-28|15:57:06.928] [Snapshots] download                     progress="64.72% 134.3GB/207.5GB" download=19.4MB/s upload=0B/s peers=5 connections=10 files=87 alloc=250.6MB sys=382.1MB
[INFO] [06-28|15:57:26.928] [Snapshots] download                     progress="64.91% 134.7GB/207.5GB" download=19.8MB/s upload=0B/s peers=5 connections=10 files=87 alloc=225.5MB sys=382.1MB
[INFO] [06-28|15:57:46.928] [Snapshots] download                     progress="65.15% 135.2GB/207.5GB" download=25.9MB/s upload=0B/s peers=8 connections=13 files=87 alloc=242.7MB sys=382.6MB
[INFO] [06-28|15:58:06.929] [Snapshots] download                     progress="65.42% 135.8GB/207.5GB" download=28.3MB/s upload=0B/s peers=12 connections=22 files=87 alloc=281.6MB sys=383.1MB
[INFO] [06-28|15:58:25.093] [p2p] GoodPeers                          eth66=4
[INFO] [06-28|15:58:26.928] [Snapshots] download                     progress="65.78% 136.5GB/207.5GB" download=38.8MB/s upload=0B/s peers=15 connections=24 files=87 alloc=255.4MB sys=411.1MB
[INFO] [06-28|15:58:46.929] [Snapshots] download                     progress="66.14% 137.2GB/207.5GB" download=37.3MB/s upload=0B/s peers=17 connections=27 files=87 alloc=285.5MB sys=421.4MB
[INFO] [06-28|15:59:06.934] [Snapshots] download                     progress="66.51% 138.0GB/207.5GB" download=39.4MB/s upload=0B/s peers=18 connections=29 files=87 alloc=291.3MB sys=421.7MB
[INFO] [06-28|15:59:26.928] [Snapshots] download                     progress="66.83% 138.7GB/207.5GB" download=34.0MB/s upload=0B/s peers=19 connections=28 files=87 alloc=258.7MB sys=421.7MB
[INFO] [06-28|15:59:46.928] [Snapshots] download                     progress="67.23% 139.5GB/207.5GB" download=43.3MB/s upload=0B/s peers=21 connections=28 files=87 alloc=159.2MB sys=421.7MB
[INFO] [06-28|16:00:06.928] [Snapshots] download                     progress="67.63% 140.3GB/207.5GB" download=42.0MB/s upload=0B/s peers=21 connections=28 files=87 alloc=247.1MB sys=421.7MB
[..]
[INFO] [06-28|16:42:26.928] [Snapshots] download                     progress="99.30% 206.1GB/207.5GB" download=18.6MB/s upload=0B/s peers=8 connections=9 files=87 alloc=172.0MB sys=464.2MB
[INFO] [06-28|16:42:46.928] [Snapshots] download                     progress="99.48% 206.4GB/207.5GB" download=19.5MB/s upload=0B/s peers=9 connections=10 files=87 alloc=213.4MB sys=464.2MB
[INFO] [06-28|16:43:06.929] [Snapshots] download                     progress="99.65% 206.8GB/207.5GB" download=17.7MB/s upload=0B/s peers=9 connections=10 files=87 alloc=283.4MB sys=464.2MB
[INFO] [06-28|16:43:26.929] [Snapshots] download                     progress="99.83% 207.2GB/207.5GB" download=19.7MB/s upload=0B/s peers=10 connections=12 files=87 alloc=176.2MB sys=464.2MB
[INFO] [06-28|16:44:15.087] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.3GB sys=2.5GB
[EROR] [06-28|16:44:15.095] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[INFO] [06-28|16:44:15.596] [Snapshots] Fetching torrent files metadata 
[INFO] [06-28|16:44:17.894] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.2GB sys=3.0GB
[EROR] [06-28|16:44:17.895] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[INFO] [06-28|16:44:18.395] [Snapshots] Fetching torrent files metadata 
[INFO] [06-28|16:44:20.542] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.4GB sys=3.3GB
[EROR] [06-28|16:44:20.542] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[INFO] [06-28|16:44:21.043] [Snapshots] Fetching torrent files metadata 
[INFO] [06-28|16:44:23.595] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.2GB sys=4.3GB
[EROR] [06-28|16:44:23.595] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[INFO] [06-28|16:44:24.095] [Snapshots] Fetching torrent files metadata 
[INFO] [06-28|16:44:25.093] [p2p] GoodPeers                          eth66=10
[INFO] [06-28|16:44:26.099] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.4GB sys=4.3GB
[EROR] [06-28|16:44:26.099] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[INFO] [06-28|16:44:26.601] [Snapshots] Fetching torrent files metadata 
[INFO] [06-28|16:44:28.883] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.0GB sys=4.3GB
[EROR] [06-28|16:44:28.884] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[INFO] [06-28|16:44:29.384] [Snapshots] Fetching torrent files metadata 
[INFO] [06-28|16:44:31.845] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.3GB sys=4.3GB
[EROR] [06-28|16:44:31.845] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[INFO] [06-28|16:44:32.345] [Snapshots] Fetching torrent files metadata 
[INFO] [06-28|16:44:34.508] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.1GB sys=4.3GB
[EROR] [06-28|16:44:34.508] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[INFO] [06-28|16:44:35.009] [Snapshots] Fetching torrent files metadata
````

**Comment by AskAlexSharov** [comment] 2022-06-29 03:09
remove `--snap.stop`

**Comment by c0deright** [comment] 2022-06-29 07:58
Works now:

```
[INFO] [06-29|09:50:07.800] [Snapshots] Stat                         blocks=0 segments=14499999 indices=0 alloc=2.1GB sys=3.6GB
[INFO] [06-29|09:50:07.800] [snapshots] Build indices                from=0
[INFO] [06-29|09:50:34.473] [snapshots] HeadersIdx                   blockNum=2500000 alloc=3.2GB sys=3.8GB
[INFO] [06-29|09:50:53.029] [snapshots] HeadersIdx                   blockNum=4500000 alloc=3.3GB sys=3.8GB
[INFO] [06-29|09:51:12.312] [snapshots] HeadersIdx                   blockNum=6500000 alloc=3.0GB sys=4.3GB
[INFO] [06-29|09:51:30.902] [snapshots] HeadersIdx                   blockNum=8500000 alloc=2.4GB sys=4.3GB
[INFO] [06-29|09:51:34.528] [p2p] GoodPeers                          eth66=0
[INFO] [06-29|09:51:49.356] [snapshots] HeadersIdx                   blockNum=10500000 alloc=3.8GB sys=4.3GB
[INFO] [06-29|09:52:08.425] [snapshots] HeadersIdx                   blockNum=13000000 alloc=3.5GB sys=4.3GB
[INFO] [06-29|09:52:32.532] [snapshots] BodiesIdx                    blockNum=500000 alloc=3.3GB sys=4.3GB
[INFO] [06-29|09:52:50.881] [snapshots] BodiesIdx                    blockNum=3500000 alloc=2.2GB sys=4.3GB
[INFO] [06-29|09:53:09.571] [snapshots] BodiesIdx                    blockNum=6500000 alloc=2.9GB sys=4.3GB
[INFO] [06-29|09:53:27.840] [snapshots] BodiesIdx                    blockNum=9500000 alloc=3.3GB sys=4.3GB
[INFO] [06-29|09:53:34.527] [p2p] GoodPeers                          eth66=1
[INFO] [06-29|09:53:52.305] [snapshots] BodiesIdx                    blockNum=13500000 alloc=2.2GB sys=4.4GB
```

Can you clarify why `--snap.stop` *(Stop producing new snapshots)* is causing this issue? I have assumed it's a setting only affecting **creation** of snapshots, not extracting downloaded snapshots.

**Comment by AskAlexSharov** [comment] 2022-06-29 08:40
Maybe we will change it in future

**Comment by mandrigin** [comment] 2022-07-05 15:01
looks like the issue is dealt with.
closing, feel free to reopen if you feel otherwise

**Closed by mandrigin** 2022-07-05 15:01 UTC

**Comment by breezytm** [comment] 2022-07-16 01:15
I am also having this exact issue but I am not using ``--snap.stop``. Any idea what may be causing the issue. Running the latest devel ver on Ubuntu. 
 
```
erigon_1      | [INFO] [07-16|00:46:29.376] [txpool] stat                            block=0 pending=1 baseFee=0 queued=180 alloc=467.2MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:46:30.268] [Snapshots] Downloading                  progress="98.96% 205.3GB/207.5GB" download=28.8MB/s upload=0B/s peers=15 connections=16 files=87
erigon_1      | [INFO] [07-16|00:46:39.401] [Snapshots] download                     progress="99.30% 206.1GB/207.5GB" download=37.0MB/s upload=0B/s peers=16 connections=16 files=87 alloc=493.2MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:46:50.280] [Snapshots] Downloading                  progress="99.30% 206.1GB/207.5GB" download=37.0MB/s upload=0B/s peers=16 connections=16 files=87
erigon_1      | [INFO] [07-16|00:46:59.403] [Snapshots] download                     progress="99.63% 206.8GB/207.5GB" download=35.1MB/s upload=0B/s peers=14 connections=14 files=87 alloc=530.5MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:47:10.268] [Snapshots] Downloading                  progress="99.63% 206.8GB/207.5GB" download=35.1MB/s upload=0B/s peers=14 connections=14 files=87
erigon_1      | [INFO] [07-16|00:47:19.402] [Snapshots] download                     progress="99.97% 207.4GB/207.5GB" download=35.5MB/s upload=0B/s peers=11 connections=11 files=87 alloc=567.2MB sys=840.2MB
erigon_1      | [INFO] [07-16|00:47:29.339] [p2p] GoodPeers                          eth66=33
erigon_1      | [INFO] [07-16|00:47:29.377] [txpool] stat                            block=0 pending=1 baseFee=0 queued=180 alloc=404.6MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:47:30.268] [Snapshots] Downloading                  progress="99.97% 207.4GB/207.5GB" download=35.5MB/s upload=0B/s peers=11 connections=11 files=87
downloader_1  | [INFO] [07-16|00:47:50.267] [Snapshots] Seeding                      up=0B/s peers=3 connections=3 files=87
downloader_1  | [INFO] [07-16|00:47:59.407] [snapshots] Verifying                    progress=17.79%
downloader_1  | [INFO] [07-16|00:48:10.268] [Snapshots] Seeding                      up=819.2PB/s peers=1 connections=1 files=87
downloader_1  | [INFO] [07-16|00:48:19.429] [snapshots] Verifying                    progress=34.79%
erigon_1      | [INFO] [07-16|00:48:29.377] [txpool] stat                            block=0 pending=1 baseFee=0 queued=180 alloc=487.7MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:48:30.268] [Snapshots] Seeding                      up=0B/s peers=2 connections=2 files=87
downloader_1  | [INFO] [07-16|00:48:39.407] [snapshots] Verifying                    progress=51.65%
downloader_1  | [INFO] [07-16|00:48:50.268] [Snapshots] Seeding                      up=0B/s peers=4 connections=4 files=87
downloader_1  | [INFO] [07-16|00:48:59.403] [snapshots] Verifying                    progress=67.77%
downloader_1  | [INFO] [07-16|00:49:10.268] [Snapshots] Seeding                      up=0B/s peers=3 connections=3 files=87
downloader_1  | [INFO] [07-16|00:49:19.403] [snapshots] Verifying                    progress=81.12%
erigon_1      | [INFO] [07-16|00:49:29.339] [p2p] GoodPeers                          eth66=33
erigon_1      | [INFO] [07-16|00:49:29.415] [txpool] stat                            block=0 pending=1 baseFee=0 queued=180 alloc=379.9MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:49:30.267] [Snapshots] Seeding                      up=0B/s peers=4 connections=4 files=87
downloader_1  | [INFO] [07-16|00:49:39.402] [snapshots] Verifying                    progress=92.34%
downloader_1  | [INFO] [07-16|00:49:50.268] [Snapshots] Seeding                      up=0B/s peers=3 connections=3 files=87
downloader_1  | [INFO] [07-16|00:49:59.404] [snapshots] Verifying                    progress=99.90%
erigon_1      | [INFO] [07-16|00:50:00.135] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=433.4MB sys=840.2MB
erigon_1      | [EROR] [07-16|00:50:00.135] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
rpcdaemon_1   | [INFO] [07-16|00:50:00.136] [Snapshots] see new                      blocks=0
erigon_1      | [INFO] [07-16|00:50:00.636] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:00.638] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=434.1MB sys=840.2MB
erigon_1      | [EROR] [07-16|00:50:00.638] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
rpcdaemon_1   | [INFO] [07-16|00:50:00.639] [Snapshots] see new                      blocks=0
erigon_1      | [INFO] [07-16|00:50:01.139] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:01.141] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=435.4MB sys=840.2MB
rpcdaemon_1   | [INFO] [07-16|00:50:01.141] [Snapshots] see new                      blocks=0
erigon_1      | [EROR] [07-16|00:50:01.141] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
erigon_1      | [INFO] [07-16|00:50:01.642] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:01.644] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=436.8MB sys=840.2MB
rpcdaemon_1   | [INFO] [07-16|00:50:01.644] [Snapshots] see new                      blocks=0
erigon_1      | [EROR] [07-16|00:50:01.644] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
erigon_1      | [INFO] [07-16|00:50:02.145] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:02.147] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=438.5MB sys=840.2MB
erigon_1      | [EROR] [07-16|00:50:02.147] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
rpcdaemon_1   | [INFO] [07-16|00:50:02.147] [Snapshots] see new                      blocks=0
erigon_1      | [INFO] [07-16|00:50:02.648] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:02.650] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=439.9MB sys=840.2MB
erigon_1      | [EROR] [07-16|00:50:02.650] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
rpcdaemon_1   | [INFO] [07-16|00:50:02.650] [Snapshots] see new                      blocks=0
```

**Comment by breezytm** [comment] 2022-07-16 01:16
my docker-compose.yml file
```
version: '2.2'

# Basic erigon's service
services:
  erigon:
    image: thorax/erigon:${TAG:-devel}
    user: root
    command: erigon ${ERIGON_FLAGS-} --datadir=/home/erigon/.local/share/erigon --private.api.addr=0.0.0.0:9090 --downloader.api.addr=downloader:9093
    volumes:
      # This is "datadir". It's ok to mount sub-dirs of "datadir" to different drives
      - ./data/erigon:/home/erigon/.local/share/erigon
    ports:
      - "30306:30303/tcp"
      - "30306:30303/udp"
    restart: unless-stopped

  downloader:
    image: thorax/erigon:${TAG:-devel}
    user: root
    command: downloader ${DOWNLOADER_FLAGS-} --downloader.api.addr=0.0.0.0:9093 --torrent.download.rate=100mb  --torrent.download.slots=6
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    volumes_from:
      - erigon
    ports: [ "42069:42069/tcp", "42069:42069/udp" ]

  rpcdaemon: # Service to server JSON-RCP API
    image: thorax/erigon:${TAG:-devel}
    user: root
    command: rpcdaemon --datadir=/home/erigon/.local/share/erigon --private.api.addr=erigon:9090 --txpool.api.addr=erigon:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,debug,net,trace,web3 --ws
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    volumes_from:
      - erigon
    ports:
      - "8585:8545"
    restart: unless-stopped
```
