### ISSUE TITLE
Erigon loops when tried stopping in execution stage

### ISSUE THREAD

**Issue by enriavil1** [ledgerwatch/erigon#5144] opened 2022-08-22 19:29 UTC
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Commit hash : bcb3cac22007af10c2270ac5de78158daa92996a

#### Expected behaviour
Stopping erigon gracefully

#### Actual behaviour
Erigon begins to loop and tries to continue stage execution giving a constant error

#### Steps to reproduce the behaviour
Get to stage execution and try stopping erigon with control C

#### Backtrace
<img width="1149" alt="Screenshot 2022-08-22 at 22 26 54" src="https://user-images.githubusercontent.com/19207637/186003023-c7502966-9790-47b0-b212-6e5d8ccd3891.png">

**Comment by wmitsuda** [comment] 2022-08-22 23:16
duplicate of #5094

**Comment by AskAlexSharov** [comment] 2022-08-26 09:32
fixed by https://github.com/ledgerwatch/erigon/pull/5194

**Comment by revitteth** [comment] 2022-08-29 09:08
Closing as fixed by #5194

**Closed by revitteth** 2022-08-29 09:08 UTC
