### ISSUE TITLE
Failed to build erigon:

### ISSUE THREAD

**Issue by skisel** [ledgerwatch/erigon#6980] opened 2023-02-27 13:58 UTC
Here is the output:

```
sergey@ip-10-9-1-233:~/erigon-2.39.0$ make erigon
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Building erigon
# github.com/prysmaticlabs/gohashtree
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: assembly failed
make: *** [Makefile:98: erigon.cmd] Error 1
```

**Comment by skisel** [comment] 2023-02-27 14:00
I tried to build few older versions, but I was getting the same error. Could you please help here? Thank you!

**Comment by AskAlexSharov** [comment] 2023-02-27 14:16
"not a git repository " means it's not a git repository 
do: git clone

**Comment by skisel** [comment] 2023-02-27 14:18
I was refering to this error here:
```
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
```

I was not building from the git repo, but I actually downloaded sources from the "Releases" section of the latest release. Should it be working?

**Comment by skisel** [comment] 2023-02-27 14:26
Same with checked out version from git:

```


sergey@ip-10-9-1-233:~/git$ git clone https://github.com/ledgerwatch/erigon.git
Cloning into 'erigon'...
remote: Enumerating objects: 192208, done.
remote: Counting objects: 100% (156/156), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 192208 (delta 109), reused 132 (delta 100), pack-reused 192052
Receiving objects: 100% (192208/192208), 246.20 MiB | 20.72 MiB/s, done.
Resolving deltas: 100% (141202/141202), done.
cd sergey@ip-10-9-1-233:~/git$ cd erigon
sergey@ip-10-9-1-233:~/git/erigon$ make erigon

Building erigon
go: downloading github.com/ledgerwatch/erigon-lib v0.0.0-20230227045411-9e95753b3a37
go: downloading github.com/urfave/cli/v2 v2.24.4
go: downloading github.com/anacrolix/torrent v1.48.1-0.20230219022425-e8971ea0f1bf
go: downloading github.com/torquem-ch/mdbx-go v0.28.2-0.20230222023854-4ec3395ee4e4
go: downloading golang.org/x/exp v0.0.0-20230224173230-c95f2b4c22f2
go: downloading github.com/huin/goupnp v1.1.0
go: downloading github.com/RoaringBitmap/roaring v1.2.3
go: downloading github.com/tidwall/btree v1.6.0
go: downloading github.com/stretchr/testify v1.8.2
go: downloading github.com/VictoriaMetrics/fastcache v1.12.1
go: downloading github.com/golang-jwt/jwt/v4 v4.5.0
go: downloading github.com/libp2p/go-libp2p-pubsub v0.9.1-0.20230221111042-3dbc2fd5baca
go: downloading github.com/ledgerwatch/erigon-snapshot v1.1.1-0.20230224032817-e29f5ad218a2
go: downloading github.com/99designs/gqlgen v0.17.24
go: downloading github.com/pion/dtls/v2 v2.2.4
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/vektah/gqlparser/v2 v2.5.1
go: downloading github.com/pion/udp v0.1.4
go: downloading github.com/agnivade/levenshtein v1.1.1
# github.com/prysmaticlabs/gohashtree
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: assembly failed


```

**Comment by AskAlexSharov** [comment] 2023-02-28 02:46
> I was refering to this error here:
> 
> ```
> asm: illegal combination: 23984 (/home/sergey/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
> ```
> 
> I was not building from the git repo, but I actually downloaded sources from the "Releases" section of the latest release. Should it be working?

I don’t know. It’s something Github does automatically. Just use “git clone” for downloading sources.

**Comment by AskAlexSharov** [comment] 2023-02-28 02:47
show: 
go env
go version

**Comment by skisel** [comment] 2023-02-28 06:48
```
sergey@ip-10-9-1-233:~$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/sergey/.cache/go-build"
GOENV="/home/sergey/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/sergey/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sergey/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2300393334=/tmp/go-build -gno-record-gcc-switches"
sergey@ip-10-9-1-233:~$ go version
go version go1.20.1 linux/arm64
```

**Comment by AskAlexSharov** [comment] 2023-03-01 09:49
@skisel what is in `cc -v`?

**Comment by skisel** [comment] 2023-03-01 09:50
```
sergey@ip-10-9-1-233:~$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
```

**Comment by AskAlexSharov** [comment] 2023-03-01 09:50
i guess https://github.com/prysmaticlabs/gohashtree/issues/6 ?

**Comment by skisel** [comment] 2023-03-01 09:51
yes, looks like it!

**Comment by AskAlexSharov** [comment] 2023-03-01 09:51
what if you download "cross-compiled binary" from releases page: https://github.com/ledgerwatch/erigon/releases ?

**Comment by skisel** [comment] 2023-03-01 09:54
the downloaded binary is fine, I was just not able to build

**Comment by Arruda9** [comment] 2023-03-09 00:48
Did this get figured out? I am seeing this behavior as well trying to go through an install.

**Comment by skisel** [comment] 2023-03-09 10:46
I have rolled back my go distribution to 1.19 and it worked

**Comment by allada** [comment] 2023-03-29 16:33
The root cause is this:
https://github.com/prysmaticlabs/gohashtree/issues/6

**Comment by AskAlexSharov** [comment] 2023-04-17 02:07
so, fixed in `devel`

**Closed by AskAlexSharov** 2023-04-17 02:07 UTC
