### ISSUE TITLE
[2/16 Headers] No block headers to write in this log period      please HELP!

### ISSUE THREAD

**Issue by BNB666666666** [ledgerwatch/erigon#6003] opened 2022-11-09 04:37 UTC
![image](https://user-images.githubusercontent.com/117515691/200607645-00fde935-78b2-4af3-b6c8-e4b664c11bef.png)

I uncompressed the 'erigon.22575695.tar.lz4' then run the erigon.           ./erigon --chain=bsc --prune=hrtc --db.pagesize=16k --datadir /run/media/xxx/新加卷/erigondata/erigon --private.api.addr=0.0.0.0:9090 -metrics --metrics.addr=0.0.0.0 --metrics.port=9350 --pprof --pprof.addr=0.0.0.0 --pprof.port=9351 --nat=any --downloader.verify --snap.stop       now it seems stucked : ( . But it can still sync super slowly（ it wrote headers around every2~3h ）. Is it resonable?  What should I do ? thx for response!

**Comment by lusiwei** [comment] 2022-11-09 12:25
和你一样的问题，尝试了删除snapshots,执行./build/bin/integration stage_headers --reset --chain=bsc --datadir=/bsc/erigon,
加--snap.stop这些都没用，还是一样

**Comment by allada** [comment] 2022-11-10 03:04
Looks like a duplicate of #5703

**Comment by du5** [comment] 2022-11-10 06:50
download new snapshots


https://github.com/BNB48Club/bsc-snapshots#erigon-snapshots

**Closed** 2022-11-10 12:53 UTC

**Comment by BNB666666666** [comment] 2022-11-27 10:50
> 和你一样的问题，尝试了删除snapshots,执行./build/bin/integration stage_headers --reset --chain=bsc --datadir=/bsc/erigon, 加--snap.stop这些都没用，还是一样

你现在同步好了吗
