### ISSUE TITLE
always stucked

### ISSUE THREAD

**Issue by lxl-CSlearner** [ledgerwatch/erigon#4025] opened 2022-04-29 06:37 UTC
The progress stucked in a bolck, and then I tried to restart the client. It looks like does work, but it stucked in a new block again a moment later.I restart  several times and it always stuck.
The client info and log as follow:
![image](https://user-images.githubusercontent.com/61180702/165895063-fc4705ff-d0d2-45a0-b000-20b9ca30edbb.png)

there are two errors in log, and it always stuck in a new blok after one time syscning.
![image](https://user-images.githubusercontent.com/61180702/165895688-ecf0f395-1971-4d79-b9fe-318fac1d0faa.png)

**Comment by AskAlexSharov** [comment] 2022-04-29 07:36
duplicate of https://github.com/ledgerwatch/erigon/issues/3964

**Closed by AskAlexSharov** 2022-04-29 07:36 UTC
