### ISSUE TITLE
eth_getTransactionReceipt returns cumulativeGasUsed of 1 and gasUsed of 0

### ISSUE THREAD

**Issue by wizzard0** [ledgerwatch/erigon#2235] opened 2021-06-25 23:56 UTC
#### System information
Erigon version: `erigon version 2021.06.5-alpha`

OS & Version: Ubuntu 20.04

Commit hash: cc360ec65854d724873bb5907d239adff1b10559

#### Expected behaviour
```
{"cumulativeGasUsed": "0xdfad27",
    "from": "0x4bc3c706ba13d5243d94625a2f6a1a20c099e08a",
    "gasUsed": "0x1e1e7",
```

#### Actual behaviour
```
{"blockHash":"0x2355b9e9d82a62eff3efc38bdc76dc3766d1e7ff4e48b2d3d1a1b72fc4dc15e2",
"blockNumber":"0xbfed57",
"contractAddress":null,
"cumulativeGasUsed":"0x1",
"from":"0x4bc3c706ba13d5243d94625a2f6a1a20c099e08a",
"gasUsed":"0x0",
"logs":[...
```
#### Steps to reproduce the behaviour
1. Sync 2021.06.04
2. Update to 2021.06.05
3. curl
```
curl -s http://127.0.0.1:8545 -X POST -H "Content-Type: application/json" -d '{"method":"eth_getTransactionReceipt","params":["0x61ada22670582505a5dd49d8a62e58df99690504b418adbeb76fbe24dc6fd7a8"],"id":1,"jsonrpc":"2.0"}'
```
Dunno if it was 0/1 before update. Is it possible to fix/rebuild without a full resync?

**Comment by alysak6075** [comment] 2021-06-27 19:27
having the same issues.

**Comment by wizzard0** [comment] 2021-06-30 10:50
@AskAlexSharov sorry, any updates? can you confirm this? should be reproduceable with 1 curl request

**Comment by AskAlexSharov** [comment] 2021-06-30 11:29
@AlexeyAkhunov found several problems in this rpc method. He will start work on it tomorrow.

**Comment by wizzard0** [comment] 2021-06-30 11:31
Cool, thanks!

**Comment by AlexeyAkhunov** [comment] 2021-07-02 10:23
@wizzard0 Can you show command line options you use to run Erigon? I cannot reproduce your issue on my database, with the version you are specifying. I wonder if your instance is trying to recompute the receipts on the fly

**Comment by AlexeyAkhunov** [comment] 2021-07-02 10:24
This is what I am getting:
```
    "blockHash": "0x2355b9e9d82a62eff3efc38bdc76dc3766d1e7ff4e48b2d3d1a1b72fc4dc15e2",
    "blockNumber": "0xbfed57",
    "contractAddress": null,
    "cumulativeGasUsed": "0xdfad27",
    "from": "0x4bc3c706ba13d5243d94625a2f6a1a20c099e08a",
    "gasUsed": "0x1e1e7",
```

**Comment by wizzard0** [comment] 2021-07-02 10:25
> @wizzard0 Can you show command line options you use to run Erigon? I cannot reproduce your issue on my database, with the version you are specifying. I wonder if your instance is trying to recompute the receipts on the fly

`./build/bin/erigon --private.api.addr 127.0.0.1:9090` :)

**Comment by AlexeyAkhunov** [comment] 2021-07-02 10:33
Hmm, weird, even with re-generating receipt by re-execution things are working (but I did find one bug, not related to this one). @wizzard0 do you have logs from when you switched Erigon to `2021.06.05` (it supposed to run a data migration to fix broken receipts) ? I wonder if something went wrong with that migration, and we need to re-run

**Comment by wizzard0** [comment] 2021-07-02 11:43
No, same results after removing and reapplying the receipts_cbor migration.

**Comment by AlexeyAkhunov** [comment] 2021-07-03 12:48
Please use this workaround (will be merged into `devel` branch soon), PR is here: https://github.com/ledgerwatch/erigon/pull/2284

```
make hack
./build/bin/hack --action scanReceipts --chaindata <datadir>/erigon/chaindata --block 12600000
```
it checks 100k blocks after given one, and every 30s it commits the changes and prints progress like this:
```
INFO [07-03|13:42:59.728] Commit                                   block=12602846 fixed=583
INFO [07-03|13:43:29.802] Commit                                   block=12603773 fixed=1146
INFO [07-03|13:43:59.724] Commit                                   block=12604261 fixed=1508
INFO [07-03|13:44:29.760] Commit                                   block=12604789 fixed=1856
INFO [07-03|13:44:59.749] Commit                                   block=12605326 fixed=2160
INFO [07-03|13:45:29.789] Commit                                   block=12605859 fixed=2499
INFO [07-03|13:45:59.783] Commit                                   block=12606402 fixed=2826
```

**Comment by AskAlexSharov** [comment] 2021-07-15 03:22
closing for now, because looks like it's fixed. feel free to re-open if need.

**Closed by AskAlexSharov** 2021-07-15 03:22 UTC
