### ISSUE TITLE
Crash during sync

### ISSUE THREAD

**Issue by SCBuergel** [ledgerwatch/erigon#5100] opened 2022-08-18 06:33 UTC
#### System information

Erigon version: 2022.08.02-alpha (unzipped from GitHub release and `make erigon` following instructions)

OS & Version: Ubuntu20.04

#### Expected behaviour
When starting my erigon node with `./erigon` I expect it to sync the chain and start operating normally.

#### Actual behaviour
Previously my node synced to about 16% but then my wifi adapter crashed so I `ctrl + c` quit erigon (was waiting for it to shut down properly). Now on next start it always just crashes, nothing that I seem to be able to do about it.
```
$ /home/seb/erigon-2022.08.02/build/bin/erigon --datadir=/home/seb/.local/share/erigon-2022.08.02
INFO[08-18|08:29:40.558] Build info                               git_branch= git_tag= git_commit=
INFO[08-18|08:29:40.558] Starting Erigon on Ethereum mainnet... 
INFO[08-18|08:29:40.563] Maximum peer count                       ETH=100 total=100
INFO[08-18|08:29:40.563] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[08-18|08:29:40.563] torrent verbosity                        level=WRN
INFO[08-18|08:29:42.884] [torrent] Public IP                      ip=178.195.164.159
INFO[08-18|08:29:42.885] Set global gas cap                       cap=50000000
INFO[08-18|08:29:42.936] Opening Database                         label=chaindata path=/home/seb/.local/share/erigon-2022.08.02/chaindata
INFO[08-18|08:29:42.938] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
INFO[08-18|08:29:42.938] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v2=false
INFO[08-18|08:29:44.000] Initialising Ethereum protocol           network=1
INFO[08-18|08:29:44.000] Disk storage enabled for ethash DAGs     dir=/home/seb/.local/share/erigon-2022.08.02/ethash-dags count=2
INFO[08-18|08:29:44.005] Starting private RPC server              on=127.0.0.1:9090
INFO[08-18|08:29:44.005] new subscription to logs established 
INFO[08-18|08:29:44.005] rpc filters: subscribing to Erigon events 
INFO[08-18|08:29:44.005] New txs subscriber joined 
EROR[08-18|08:29:44.006] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="[main.go:29 panic.go:838 panic.go:220 signal_unix.go:818 index.go:149 block_snapshots.go:179 config.go:245 block_snapshots.go:286 config.go:243 backend.go:572 node.go:115 main.go:58 app.go:526 app.go:286 main.go:34 proc.go:250 asm_amd64.s:1571]"
seb@sebox:~$ /home/seb/erigon-2022.08.02/build/bin/erigon --datadir=/home/seb/.local/share/erigon-2022.08.02
INFO[08-18|08:29:53.528] Build info                               git_branch= git_tag= git_commit=
INFO[08-18|08:29:53.529] Starting Erigon on Ethereum mainnet... 
INFO[08-18|08:29:53.529] Maximum peer count                       ETH=100 total=100
INFO[08-18|08:29:53.529] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[08-18|08:29:53.529] torrent verbosity                        level=WRN
INFO[08-18|08:29:55.848] [torrent] Public IP                      ip=178.195.164.159
INFO[08-18|08:29:55.848] Set global gas cap                       cap=50000000
INFO[08-18|08:29:55.879] Opening Database                         label=chaindata path=/home/seb/.local/share/erigon-2022.08.02/chaindata
INFO[08-18|08:29:55.880] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
INFO[08-18|08:29:55.880] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v2=false
INFO[08-18|08:29:56.631] Initialising Ethereum protocol           network=1
INFO[08-18|08:29:56.631] Disk storage enabled for ethash DAGs     dir=/home/seb/.local/share/erigon-2022.08.02/ethash-dags count=2
INFO[08-18|08:29:56.645] Starting private RPC server              on=127.0.0.1:9090
INFO[08-18|08:29:56.645] new subscription to logs established 
INFO[08-18|08:29:56.645] rpc filters: subscribing to Erigon events 
INFO[08-18|08:29:56.645] New txs subscriber joined 
EROR[08-18|08:29:56.645] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="[main.go:29 panic.go:838 panic.go:220 signal_unix.go:818 index.go:149 block_snapshots.go:179 config.go:245 block_snapshots.go:286 config.go:243 backend.go:572 node.go:115 main.go:58 app.go:526 app.go:286 main.go:34 proc.go:250 asm_amd64.s:1571]"

```
#### Steps to reproduce the behaviour
`./erigon`

**Comment by 3nprob** [comment] 2022-08-18 07:00
Duplicate of #5068

**Closed** 2022-08-18 08:41 UTC
