### ISSUE TITLE
TRANSACTIONS_66, error parsing transaction payload

### ISSUE THREAD

**Issue by asselinpaul** [ledgerwatch/erigon#3165] opened 2021-12-24 10:22 UTC
#### System information

Erigon version: `erigon version 2021.12.3-beta`

OS & Version: `Linux`

#### Expected behaviour

working node

#### Actual behaviour

lots of errors, not sure how to debug (problem with erigon, network, machine itself)

#### Backtrace

````
[WARN] [12-24|11:16:42.058] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:42.059] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:42.228] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:42.672] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:43.108] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:43.130] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:43.140] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:43.417] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: nonce: uint64 must be a string, not isList"
[WARN] [12-24|11:16:43.617] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:44.016] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:44.100] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:44.171] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:44.428] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:45.057] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:45.100] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:45.885] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:46.200] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:46.706] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:47.018] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: nonce: uint64 must be a string, not isList"
[WARN] [12-24|11:16:47.359] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:47.473] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:47.703] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:47.708] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:47.757] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:48.017] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:48.386] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-24|11:16:48.617] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-24|11:16:48.929] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
````

#### Drive space

```
Filesystem      1K-blocks       Used  Available Use% Mounted on
udev             65883984          0   65883984   0% /dev
tmpfs            13189656       2232   13187424   1% /run
/dev/md2       2077506936 1755345204  216560352  90% /
tmpfs            65948272          0   65948272   0% /dev/shm
tmpfs                5120          0       5120   0% /run/lock
tmpfs            65948272          0   65948272   0% /sys/fs/cgroup
/dev/md1           498532     371845     100524  79% /boot
/dev/md3       1607357816     184680 1525454080   1% /home
```

90% full, could it be causing problems?

**Comment by susuper** [comment] 2021-12-24 11:36
I've got the same issue. About 70% of drive space is free.

**Comment by AskAlexSharov** [comment] 2021-12-25 05:30
“ 90% full, could it be causing problems? ”
No, fixed by https://github.com/ledgerwatch/erigon/pull/3156

**Comment by splix** [comment] 2021-12-26 18:30
Having the same issue in the past week or so

**Comment by KryptoBillah** [comment] 2021-12-26 18:49
Seeing the same issue in the past week or so. Not sure if I should shut off the node.

**Comment by AskAlexSharov** [comment] 2021-12-27 01:17
Fixed in devel and stable branches

**Comment by mtake** [comment] 2021-12-29 08:50
Having the same issue with 2021.12.2-beta (not 2021.12.3-beta). Can I safely ignore the warnings until a new beta version that includes the fix is released?

**Comment by AskAlexSharov** [comment] 2021-12-29 09:45
> Having the same issue with 2021.12.2-beta (not 2021.12.3-beta). Can I safely ignore the warnings until a new beta version that includes the fix is released?

Yes.

**Comment by BirdyUK** [comment] 2021-12-29 20:28
I have also just experienced this which started just after the following sequence:

```

[INFO] [12-29|20:12:28.192] [p2p] GoodPeers                          eth66=33
[INFO] [12-29|20:12:33.273] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=eab22600... alloc="837.8 MiB" sys="6.7 GiB"
[INFO] [12-29|20:13:03.274] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=ee8b86f8... alloc="504.7 MiB" sys="6.7 GiB"
[INFO] [12-29|20:13:33.273] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=f0d622a8... alloc="650.0 MiB" sys="6.7 GiB"
[INFO] [12-29|20:14:03.273] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=f4a12dba... alloc="677.7 MiB" sys="6.7 GiB"
[INFO] [12-29|20:14:28.191] [p2p] GoodPeers                          eth66=33
[INFO] [12-29|20:14:33.273] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=f86225ab... alloc="661.2 MiB" sys="6.7 GiB"
[INFO] [12-29|20:15:03.274] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=fc2d033b... alloc="705.3 MiB" sys="6.7 GiB"
[INFO] [12-29|20:15:32.787] [13/15 TxLookup] etl: temp files removed total size="51.2 GB"
[INFO] [12-29|20:16:17.666] [13/15 TxLookup] DONE                    in=10h51m54.832120031s
[INFO] [12-29|20:16:17.757] RPC Daemon notified of new headers       from=13876576 to=13877600
[INFO] [12-29|20:16:17.758] [1/15 Headers] Waiting for headers...    from=13877600
[INFO] [12-29|20:16:19.520] [1/15 Headers] Processed                 highest inserted=13877602 age=3d19h45m
[INFO] [12-29|20:16:21.245] [5/15 Execution] Completed on            block=13877602
[INFO] [12-29|20:16:28.192] [p2p] GoodPeers                          eth66=32
[INFO] [12-29|20:16:35.073] RPC Daemon notified of new headers       from=13877600 to=13877602
[INFO] [12-29|20:16:35.073] [1/15 Headers] Waiting for headers...    from=13877602
[INFO] [12-29|20:16:35.124] [txpool] Started
[WARN] [12-29|20:16:35.799] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-29|20:16:36.400] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-29|20:16:36.941] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-29|20:16:38.899] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-29|20:16:39.899] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-29|20:16:40.041] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"

```

In terms of space being an issue, i have the following configuration:

Ram:   512GB  (Approx 60gb in use)
Disk:   12x 15TB NVME (180TB in raid giving total usable disk space of ~90TB and 70tb of that allocated to a nodes mnt that holds chain data with currently approx 3tb used)

```
root@ns305159:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
nodes            73T  2.9T   70T   4% /nodes
```

So i can confirm this is not related to ram, disk, cpu or networking.


Thanks

**Comment by BirdyUK** [comment] 2021-12-29 20:40
I have also just experienced this which started just after the following sequence:

```

[INFO] [12-29|20:12:28.192] [p2p] GoodPeers                          eth66=33
[INFO] [12-29|20:12:33.273] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=eab22600... alloc="837.8 MiB" sys="6.7 GiB"
[INFO] [12-29|20:13:03.274] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=ee8b86f8... alloc="504.7 MiB" sys="6.7 GiB"
[INFO] [12-29|20:13:33.273] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=f0d622a8... alloc="650.0 MiB" sys="6.7 GiB"
[INFO] [12-29|20:14:03.273] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=f4a12dba... alloc="677.7 MiB" sys="6.7 GiB"
[INFO] [12-29|20:14:28.191] [p2p] GoodPeers                          eth66=33
[INFO] [12-29|20:14:33.273] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=f86225ab... alloc="661.2 MiB" sys="6.7 GiB"
[INFO] [12-29|20:15:03.274] [13/15 TxLookup] ETL [2/2] Loading       into=BlockTransactionLookup current key=fc2d033b... alloc="705.3 MiB" sys="6.7 GiB"
[INFO] [12-29|20:15:32.787] [13/15 TxLookup] etl: temp files removed total size="51.2 GB"
[INFO] [12-29|20:16:17.666] [13/15 TxLookup] DONE                    in=10h51m54.832120031s
[INFO] [12-29|20:16:17.757] RPC Daemon notified of new headers       from=13876576 to=13877600
[INFO] [12-29|20:16:17.758] [1/15 Headers] Waiting for headers...    from=13877600
[INFO] [12-29|20:16:19.520] [1/15 Headers] Processed                 highest inserted=13877602 age=3d19h45m
[INFO] [12-29|20:16:21.245] [5/15 Execution] Completed on            block=13877602
[INFO] [12-29|20:16:28.192] [p2p] GoodPeers                          eth66=32
[INFO] [12-29|20:16:35.073] RPC Daemon notified of new headers       from=13877600 to=13877602
[INFO] [12-29|20:16:35.073] [1/15 Headers] Waiting for headers...    from=13877602
[INFO] [12-29|20:16:35.124] [txpool] Started
[WARN] [12-29|20:16:35.799] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: envelope Prefix: must be a list"
[WARN] [12-29|20:16:36.400] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-29|20:16:36.941] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-29|20:16:38.899] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-29|20:16:39.899] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"
[WARN] [12-29|20:16:40.041] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="parse transaction payload: transaction must be either 1 list or 1 string"

```

In terms of space being an issue, i have the following configuration:

**Ram**:   512GB  (Approx 60gb in use)
**Disk**:   12x 15TB NVME (180TB in raid giving total usable disk space of ~90TB and 70tb of that allocated to a nodes mnt that holds chain data with currently approx 3tb used)

```
df -h
Filesystem      Size  Used Avail Use% Mounted on
nodes            73T  2.9T   70T   4% /nodes
```


I have been waiting a few days now for the sync to complete, i believe its not far off completing now 


```
> eth.syncing
{
  currentBlock: 13877602,
  highestBlock: 13884321,
  stages: [{
      block_number: "0xd3dba1",
      stage_name: "Headers"
  }, {
      block_number: "0xd3dba1",
      stage_name: "BlockHashes"
  }, {
      block_number: "0xd3dba1",
      stage_name: "Bodies"
  }, {
      block_number: "0xd3dba1",
      stage_name: "Senders"
  }, {
      block_number: "0xd3dba1",
      stage_name: "Execution"
  }, {
      block_number: "0x0",
      stage_name: "Translation"
  }, {
      block_number: "0xd3c162",
      stage_name: "HashState"
  }, {
      block_number: "0xd3c162",
      stage_name: "IntermediateHashes"
  }, {
      block_number: "0xd3c162",
      stage_name: "AccountHistoryIndex"
  }, {
      block_number: "0xd3c162",
      stage_name: "StorageHistoryIndex"
  }, {
      block_number: "0xd3c162",
      stage_name: "LogIndex"
  }, {
      block_number: "0xd3c162",
      stage_name: "CallTraces"
  }, {
      block_number: "0xd3c162",
      stage_name: "TxLookup"
  }, {
      block_number: "0x0",
      stage_name: "TxPool"
  }, {
      block_number: "0xd3c162",
      stage_name: "Finish"
  }],
  startingBlock: 0
}
>

```

So i can confirm this is not related to ram, disk, cpu or networking.


Thanks

**Comment by KryptoBillah** [comment] 2021-12-29 21:28
> Fixed in devel and stable branches

I got help from @tjayrush. All I had to do was stop the sync then git pull to re-build the node. 

(Steps for newbies like me) 
Step 1: Stop the sync (control + C, depends on your machine)
Step 2: "git pull" 
Step 3: "make all" 

It's been running smoothly since. Thank you all.

**Comment by u39kun** [comment] 2021-12-30 18:34
@AskAlexSharov Why do you think is the reason is for so many RLP decoding issues?  Is this something new that we are observing?  Is this some kind of spam/DoS attack to slow other nodes down to gain some advantage, or is there some bad library/client code out there that's not RLP encoding correctly?  I'm new to running an Ethereum node and just trying to learn :)

**Comment by AskAlexSharov** [comment] 2021-12-31 01:05
Some bad node with incorrect Eth66 support

**Comment by AskAlexSharov** [comment] 2022-01-20 15:32
Done

**Closed by AskAlexSharov** 2022-01-20 15:32 UTC
