### ISSUE TITLE
StageBodies: shows network download spikes, with low average

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#6129] opened 2022-11-25 11:09 UTC
Mainnet:
<img width="622" alt="Screenshot 2022-11-25 at 18 08 06" src="https://user-images.githubusercontent.com/46885206/203972803-8a6fb63a-dbc3-4778-8c6c-30502c961fee.png">

I also see spikes in logs (StageBodies does print log very rare, not every 30 sec):
```
[INFO] [11-25|09:40:04.521] [2/16 Headers] Fork choice: chain extension from=15843286 to=16046161
[INFO] [11-25|09:40:10.666] [5/16 Bodies] Processing bodies...       from=15843286 to=16046161

[INFO] [11-25|09:40:32.217] [LightClient] P2P                        peers=5
[INFO] [11-25|09:40:32.624] [5/16 Bodies] Writing block bodies       block_num=15843315 remaining=202846 alloc=3.6GB sys=5.1GB
[INFO] [11-25|09:40:32.655] [5/16 Bodies] Downloading block bodies   block_num=15843315 delivery/sec=4.7MB wasted/sec=0B remaining=202845 delivered=1249 alloc=3.6GB sys=5.1GB
[INFO] [11-25|09:40:50.061] [5/16 Bodies] Writing block bodies       block_num=15843345 remaining=202816 alloc=2.9GB sys=5.3GB
[INFO] [11-25|09:41:20.145] [p2p] GoodPeers                          eth66=14 eth67=14
[INFO] [11-25|09:41:24.266] [5/16 Bodies] Writing block bodies       block_num=15843371 remaining=202790 alloc=3.2GB sys=5.4GB
[INFO] [11-25|09:41:24.266] [5/16 Bodies] Downloading block bodies   block_num=15843371 delivery/sec=10.7MB wasted/sec=0B remaining=202815 delivered=4178 alloc=3.2GB sys=5.4GB
[INFO] [11-25|09:41:32.218] [LightClient] P2P                        peers=5
[INFO] [11-25|09:42:00.057] [5/16 Bodies] Downloading block bodies   block_num=15843371 delivery/sec=7.1MB wasted/sec=0B remaining=202789 delivered=6106 alloc=3.8GB sys=5.4GB
[INFO] [11-25|09:42:26.320] [5/16 Bodies] Downloading block bodies   block_num=15843371 delivery/sec=4.9MB wasted/sec=0B remaining=202789 delivered=7501 alloc=3.3GB sys=5.4GB
[INFO] [11-25|09:42:32.217] [LightClient] P2P                        peers=6
[INFO] [11-25|09:42:56.032] [5/16 Bodies] Downloading block bodies   block_num=15843371 delivery/sec=5.4MB wasted/sec=0B remaining=202789 delivered=9013 alloc=3.2GB sys=5.4GB
[INFO] [11-25|09:43:20.146] [p2p] GoodPeers                          eth66=16 eth67=14
[INFO] [11-25|09:43:32.217] [LightClient] P2P                        peers=10
[INFO] [11-25|09:43:43.016] [5/16 Bodies] Writing block bodies       block_num=15843396 remaining=202765 alloc=4.0GB sys=5.4GB
[INFO] [11-25|09:43:43.016] [5/16 Bodies] Downloading block bodies   block_num=15843396 delivery/sec=8.3MB wasted/sec=0B remaining=202789 delivered=11345 alloc=4.0GB sys=5.4GB
[INFO] [11-25|09:44:32.218] [LightClient] P2P                        peers=11
[INFO] [11-25|09:44:37.009] [5/16 Bodies] Writing block bodies       block_num=15843456 remaining=202705 alloc=2.9GB sys=5.4GB
[INFO] [11-25|09:44:37.042] [5/16 Bodies] Downloading block bodies   block_num=15843456 delivery/sec=8.5MB wasted/sec=0B remaining=202704 delivered=13677 alloc=2.9GB sys=5.4GB
[INFO] [11-25|09:45:20.145] [p2p] GoodPeers                          eth66=22 eth67=18
[INFO] [11-25|09:45:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|09:45:35.978] [5/16 Bodies] Writing block bodies       block_num=15843515 remaining=202646 alloc=2.7GB sys=5.4GB
[INFO] [11-25|09:45:35.978] [5/16 Bodies] Downloading block bodies   block_num=15843515 delivery/sec=8.6MB wasted/sec=0B remaining=202704 delivered=16050 alloc=2.7GB sys=5.4GB
[INFO] [11-25|09:46:32.217] [LightClient] P2P                        peers=10
[INFO] [11-25|09:46:34.533] [5/16 Bodies] Writing block bodies       block_num=15843600 remaining=202561 alloc=4.1GB sys=5.4GB
[INFO] [11-25|09:46:34.569] [5/16 Bodies] Downloading block bodies   block_num=15843600 delivery/sec=7.7MB wasted/sec=0B remaining=202560 delivered=18151 alloc=4.1GB sys=5.4GB
[INFO] [11-25|09:47:20.146] [p2p] GoodPeers                          eth66=23 eth67=18
[INFO] [11-25|09:47:32.217] [LightClient] P2P                        peers=9
[INFO] [11-25|09:47:35.198] [5/16 Bodies] Writing block bodies       block_num=15843722 remaining=202439 alloc=2.7GB sys=5.4GB
[INFO] [11-25|09:47:35.198] [5/16 Bodies] Downloading block bodies   block_num=15843722 delivery/sec=7.3MB wasted/sec=0B remaining=202560 delivered=20122 alloc=2.7GB sys=5.4GB
[INFO] [11-25|09:48:32.218] [LightClient] P2P                        peers=11
[INFO] [11-25|09:48:39.637] [5/16 Bodies] Writing block bodies       block_num=15843857 remaining=202304 alloc=4.0GB sys=5.4GB
[INFO] [11-25|09:48:39.637] [5/16 Bodies] Downloading block bodies   block_num=15843857 delivery/sec=7.2MB wasted/sec=0B remaining=202438 delivered=22051 alloc=4.0GB sys=5.4GB
[INFO] [11-25|09:49:20.145] [p2p] GoodPeers                          eth66=27 eth67=19
[INFO] [11-25|09:49:32.218] [LightClient] P2P                        peers=10
[INFO] [11-25|09:49:46.947] [5/16 Bodies] Downloading block bodies   block_num=15843857 delivery/sec=7.0MB wasted/sec=0B remaining=202303 delivered=23932 alloc=2.6GB sys=5.4GB
[INFO] [11-25|09:50:32.218] [LightClient] P2P                        peers=11
[INFO] [11-25|09:50:56.262] [5/16 Bodies] Downloading block bodies   block_num=15843857 delivery/sec=6.8MB wasted/sec=0B remaining=202303 delivered=25743 alloc=3.2GB sys=5.4GB
[INFO] [11-25|09:51:20.145] [p2p] GoodPeers                          eth66=26 eth67=18
[INFO] [11-25|09:51:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|09:52:03.307] [5/16 Bodies] Writing block bodies       block_num=15843968 remaining=202193 alloc=3.8GB sys=5.4GB
[INFO] [11-25|09:52:03.344] [5/16 Bodies] Downloading block bodies   block_num=15843968 delivery/sec=5.6MB wasted/sec=0B remaining=202192 delivered=27282 alloc=3.8GB sys=5.4GB
[INFO] [11-25|09:52:32.218] [LightClient] P2P                        peers=11
[INFO] [11-25|09:53:11.971] [5/16 Bodies] Writing block bodies       block_num=15844276 remaining=201885 alloc=3.8GB sys=5.4GB
[INFO] [11-25|09:53:11.971] [5/16 Bodies] Downloading block bodies   block_num=15844276 delivery/sec=4.9MB wasted/sec=0B remaining=202192 delivered=28658 alloc=3.8GB sys=5.4GB
[INFO] [11-25|09:53:20.145] [p2p] GoodPeers                          eth66=28 eth67=19
[INFO] [11-25|09:53:32.217] [LightClient] P2P                        peers=11
[INFO] [11-25|09:54:20.136] [5/16 Bodies] Writing block bodies       block_num=15844627 remaining=201534 alloc=3.8GB sys=5.4GB
[INFO] [11-25|09:54:20.136] [5/16 Bodies] Downloading block bodies   block_num=15844627 delivery/sec=4.1MB wasted/sec=0B remaining=201884 delivered=29731 alloc=3.8GB sys=5.4GB
[INFO] [11-25|09:54:32.217] [LightClient] P2P                        peers=11
[INFO] [11-25|09:55:20.145] [p2p] GoodPeers                          eth66=30 eth67=20
[INFO] [11-25|09:55:25.713] [5/16 Bodies] Writing block bodies       block_num=15844859 remaining=201302 alloc=3.3GB sys=5.4GB
[INFO] [11-25|09:55:25.714] [5/16 Bodies] Downloading block bodies   block_num=15844859 delivery/sec=3.5MB wasted/sec=0B remaining=201533 delivered=30657 alloc=3.3GB sys=5.4GB
[INFO] [11-25|09:55:32.218] [LightClient] P2P                        peers=10
[INFO] [11-25|09:56:32.217] [LightClient] P2P                        peers=9
[INFO] [11-25|09:56:35.340] [5/16 Bodies] Writing block bodies       block_num=15845186 remaining=200975 alloc=3.0GB sys=5.4GB
[INFO] [11-25|09:56:35.341] [5/16 Bodies] Downloading block bodies   block_num=15845186 delivery/sec=3.0MB wasted/sec=0B remaining=201301 delivered=31464 alloc=3.0GB sys=5.4GB
[INFO] [11-25|09:57:20.145] [p2p] GoodPeers                          eth66=33 eth67=22
[INFO] [11-25|09:57:32.218] [LightClient] P2P                        peers=10
[INFO] [11-25|09:57:44.941] [5/16 Bodies] Writing block bodies       block_num=15845658 remaining=200503 alloc=2.4GB sys=5.4GB
[INFO] [11-25|09:57:44.941] [5/16 Bodies] Downloading block bodies   block_num=15845658 delivery/sec=2.6MB wasted/sec=0B remaining=200974 delivered=32138 alloc=2.4GB sys=5.4GB
[INFO] [11-25|09:58:32.217] [LightClient] P2P                        peers=12
[INFO] [11-25|09:58:54.519] [5/16 Bodies] Writing block bodies       block_num=15845992 remaining=200169 alloc=4.0GB sys=5.4GB
[INFO] [11-25|09:58:54.536] [5/16 Bodies] Downloading block bodies   block_num=15845992 delivery/sec=2.5MB wasted/sec=0B remaining=200168 delivered=32837 alloc=4.0GB sys=5.4GB
[INFO] [11-25|09:59:20.145] [p2p] GoodPeers                          eth66=33 eth67=22
[INFO] [11-25|09:59:32.217] [LightClient] P2P                        peers=12
[INFO] [11-25|10:00:08.616] [5/16 Bodies] Writing block bodies       block_num=15846613 remaining=199548 alloc=3.7GB sys=5.4GB
[INFO] [11-25|10:00:08.616] [5/16 Bodies] Downloading block bodies   block_num=15846613 delivery/sec=2.2MB wasted/sec=0B remaining=200168 delivered=33428 alloc=3.7GB sys=5.4GB
[INFO] [11-25|10:00:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|10:01:13.472] [5/16 Bodies] Downloading block bodies   block_num=15846613 delivery/sec=1.7MB wasted/sec=0B remaining=199547 delivered=33919 alloc=2.5GB sys=5.4GB
[INFO] [11-25|10:01:20.145] [p2p] GoodPeers                          eth66=32 eth67=23
[INFO] [11-25|10:01:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|10:02:17.395] [5/16 Bodies] Downloading block bodies   block_num=15846613 delivery/sec=1.3MB wasted/sec=0B remaining=199547 delivered=34297 alloc=3.5GB sys=5.4GB
[INFO] [11-25|10:02:32.218] [LightClient] P2P                        peers=14
[INFO] [11-25|10:03:20.145] [p2p] GoodPeers                          eth66=32 eth67=23
[INFO] [11-25|10:03:26.359] [5/16 Bodies] Writing block bodies       block_num=15846910 remaining=199251 alloc=3.0GB sys=5.4GB
[INFO] [11-25|10:03:26.371] [5/16 Bodies] Downloading block bodies   block_num=15846910 delivery/sec=1.4MB wasted/sec=0B remaining=199250 delivered=34701 alloc=3.0GB sys=5.4GB
[INFO] [11-25|10:03:32.217] [LightClient] P2P                        peers=13
[INFO] [11-25|10:04:29.294] [5/16 Bodies] Downloading block bodies   block_num=15846910 delivery/sec=951.7KB wasted/sec=0B remaining=199250 delivered=34978 alloc=3.9GB sys=5.4GB
[INFO] [11-25|10:04:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|10:05:20.146] [p2p] GoodPeers                          eth66=33 eth67=26
[INFO] [11-25|10:05:32.218] [LightClient] P2P                        peers=12
[INFO] [11-25|10:05:43.917] [5/16 Bodies] Writing block bodies       block_num=15847693 remaining=198468 alloc=3.3GB sys=5.4GB
[INFO] [11-25|10:05:43.934] [5/16 Bodies] Downloading block bodies   block_num=15847693 delivery/sec=1.1MB wasted/sec=0B remaining=198467 delivered=35268 alloc=3.3GB sys=5.4GB
[INFO] [11-25|10:06:32.218] [LightClient] P2P                        peers=15
[INFO] [11-25|10:07:14.158] [5/16 Bodies] Writing block bodies       block_num=15849641 remaining=196520 alloc=3.2GB sys=5.4GB
[INFO] [11-25|10:07:14.159] [5/16 Bodies] Downloading block bodies   block_num=15849641 delivery/sec=1.5MB wasted/sec=0B remaining=198467 delivered=35742 alloc=3.2GB sys=5.4GB
[INFO] [11-25|10:07:20.146] [p2p] GoodPeers                          eth66=33 eth67=27
[INFO] [11-25|10:07:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|10:08:32.218] [LightClient] P2P                        peers=12
[INFO] [11-25|10:08:48.004] [5/16 Bodies] Writing block bodies       block_num=15850732 remaining=195429 alloc=3.7GB sys=5.4GB
[INFO] [11-25|10:08:48.004] [5/16 Bodies] Downloading block bodies   block_num=15850732 delivery/sec=2.8MB wasted/sec=0B remaining=196519 delivered=36541 alloc=3.7GB sys=5.4GB
[INFO] [11-25|10:09:20.145] [p2p] GoodPeers                          eth66=32 eth67=27
[INFO] [11-25|10:09:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|10:10:32.218] [LightClient] P2P                        peers=14
[INFO] [11-25|10:10:39.086] [5/16 Bodies] Writing block bodies       block_num=15853166 remaining=192995 alloc=2.8GB sys=5.4GB
[INFO] [11-25|10:10:39.136] [5/16 Bodies] Downloading block bodies   block_num=15853166 delivery/sec=2.6MB wasted/sec=0B remaining=192994 delivered=37243 alloc=2.8GB sys=5.4GB
[INFO] [11-25|10:11:20.145] [p2p] GoodPeers                          eth66=32 eth67=30
[INFO] [11-25|10:11:32.218] [LightClient] P2P                        peers=12
[INFO] [11-25|10:12:32.218] [LightClient] P2P                        peers=12
[INFO] [11-25|10:12:32.727] Got beacon block by root handler call
[INFO] [11-25|10:12:37.513] [5/16 Bodies] Writing block bodies       block_num=15854984 remaining=191177 alloc=4.1GB sys=5.4GB
[INFO] [11-25|10:12:37.558] [5/16 Bodies] Downloading block bodies   block_num=15854984 delivery/sec=4.3MB wasted/sec=0B remaining=191176 delivered=38428 alloc=4.1GB sys=5.4GB
[INFO] [11-25|10:13:20.145] [p2p] GoodPeers                          eth66=33 eth67=29
[INFO] [11-25|10:13:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|10:14:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|10:14:50.305] [5/16 Bodies] Writing block bodies       block_num=15857137 remaining=189024 alloc=3.3GB sys=5.4GB
[INFO] [11-25|10:14:50.356] [5/16 Bodies] Downloading block bodies   block_num=15857137 delivery/sec=4.8MB wasted/sec=0B remaining=189023 delivered=39806 alloc=3.3GB sys=5.4GB
[INFO] [11-25|10:15:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:15:32.218] [LightClient] P2P                        peers=14
[INFO] [11-25|10:16:32.218] [LightClient] P2P                        peers=13
[INFO] [11-25|10:17:20.146] [p2p] GoodPeers                          eth66=33 eth67=31
[INFO] [11-25|10:17:28.658] [5/16 Bodies] Writing block bodies       block_num=15860913 remaining=185248 alloc=3.6GB sys=5.4GB
[INFO] [11-25|10:17:28.658] [5/16 Bodies] Downloading block bodies   block_num=15860913 delivery/sec=5.4MB wasted/sec=0B remaining=189023 delivered=41346 alloc=3.6GB sys=5.4GB
[INFO] [11-25|10:17:32.217] [LightClient] P2P                        peers=14
[INFO] [11-25|10:18:32.218] [LightClient] P2P                        peers=14
[INFO] [11-25|10:19:20.145] [p2p] GoodPeers                          eth66=33 eth67=30
[INFO] [11-25|10:19:32.218] [LightClient] P2P                        peers=14
[INFO] [11-25|10:20:32.162] [5/16 Bodies] Writing block bodies       block_num=15864908 remaining=181253 alloc=3.7GB sys=5.5GB
[INFO] [11-25|10:20:32.197] [5/16 Bodies] Downloading block bodies   block_num=15864908 delivery/sec=7.3MB wasted/sec=0B remaining=181252 delivered=43379 alloc=3.7GB sys=5.5GB
[INFO] [11-25|10:20:32.217] [LightClient] P2P                        peers=14
[INFO] [11-25|10:21:20.145] [p2p] GoodPeers                          eth66=32 eth67=32
[INFO] [11-25|10:21:32.218] [LightClient] P2P                        peers=15
[INFO] [11-25|10:22:32.217] [LightClient] P2P                        peers=15
[INFO] [11-25|10:23:20.145] [p2p] GoodPeers                          eth66=32 eth67=33
[INFO] [11-25|10:23:32.218] [LightClient] P2P                        peers=16
[INFO] [11-25|10:23:59.967] [5/16 Bodies] Writing block bodies       block_num=15869386 remaining=176775 alloc=3.7GB sys=5.6GB
[INFO] [11-25|10:24:00.005] [5/16 Bodies] Downloading block bodies   block_num=15869386 delivery/sec=8.9MB wasted/sec=0B remaining=176774 delivered=45890 alloc=3.7GB sys=5.6GB
[INFO] [11-25|10:24:32.218] [LightClient] P2P                        peers=15
[INFO] [11-25|10:25:20.145] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:25:32.217] [LightClient] P2P                        peers=16
[INFO] [11-25|10:26:32.218] [LightClient] P2P                        peers=17
[INFO] [11-25|10:27:20.145] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:27:32.218] [LightClient] P2P                        peers=17
[INFO] [11-25|10:28:25.635] [5/16 Bodies] Writing block bodies       block_num=15876828 remaining=169333 alloc=3.5GB sys=5.8GB
[INFO] [11-25|10:28:25.677] [5/16 Bodies] Downloading block bodies   block_num=15876828 delivery/sec=10.0MB wasted/sec=0B remaining=169332 delivered=48677 alloc=3.5GB sys=5.8GB
[INFO] [11-25|10:28:32.218] [LightClient] P2P                        peers=17
[INFO] [11-25|10:29:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:29:32.218] [LightClient] P2P                        peers=17
[INFO] [11-25|10:30:32.217] [LightClient] P2P                        peers=17
[INFO] [11-25|10:31:20.145] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:31:32.218] [LightClient] P2P                        peers=18
[INFO] [11-25|10:32:06.435] [5/16 Bodies] Writing block bodies       block_num=15877936 remaining=168225 alloc=3.0GB sys=6.0GB
[INFO] [11-25|10:32:06.473] [5/16 Bodies] Downloading block bodies   block_num=15877936 delivery/sec=12.0MB wasted/sec=0B remaining=168224 delivered=52114 alloc=3.0GB sys=6.0GB
[INFO] [11-25|10:32:32.218] [LightClient] P2P                        peers=16
[INFO] [11-25|10:33:20.146] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:33:32.217] [LightClient] P2P                        peers=16
[INFO] [11-25|10:34:32.217] [LightClient] P2P                        peers=16
[INFO] [11-25|10:35:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:35:32.218] [LightClient] P2P                        peers=17
[INFO] [11-25|10:36:07.702] [5/16 Bodies] Writing block bodies       block_num=15879477 remaining=166684 alloc=2.4GB sys=6.0GB
[INFO] [11-25|10:36:07.702] [5/16 Bodies] Downloading block bodies   block_num=15879477 delivery/sec=11.0MB wasted/sec=0B remaining=168224 delivered=55312 alloc=2.4GB sys=6.0GB
[INFO] [11-25|10:36:32.217] [LightClient] P2P                        peers=17
[INFO] [11-25|10:37:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:37:32.218] [LightClient] P2P                        peers=16
[INFO] [11-25|10:38:32.217] [LightClient] P2P                        peers=16
[INFO] [11-25|10:39:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:39:32.218] [LightClient] P2P                        peers=16
[INFO] [11-25|10:40:21.664] [5/16 Bodies] Writing block bodies       block_num=15879783 remaining=166378 alloc=4.7GB sys=6.1GB
[INFO] [11-25|10:40:21.664] [5/16 Bodies] Downloading block bodies   block_num=15879783 delivery/sec=10.6MB wasted/sec=0B remaining=166683 delivered=58267 alloc=4.7GB sys=6.1GB
[INFO] [11-25|10:40:32.217] [LightClient] P2P                        peers=16
[INFO] [11-25|10:41:20.145] [p2p] GoodPeers                          eth66=32 eth67=33
[INFO] [11-25|10:41:32.217] [LightClient] P2P                        peers=16
[INFO] [11-25|10:42:32.217] [LightClient] P2P                        peers=16
[INFO] [11-25|10:43:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:43:32.217] [LightClient] P2P                        peers=16
[INFO] [11-25|10:44:32.218] [LightClient] P2P                        peers=17
[INFO] [11-25|10:44:56.233] [5/16 Bodies] Downloading block bodies   block_num=15879783 delivery/sec=8.4MB wasted/sec=0B remaining=166377 delivered=60624 alloc=4.0GB sys=6.1GB
[INFO] [11-25|10:45:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:45:32.218] [LightClient] P2P                        peers=18
[INFO] [11-25|10:46:32.217] [LightClient] P2P                        peers=19
[INFO] [11-25|10:47:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:47:32.217] [LightClient] P2P                        peers=19
[INFO] [11-25|10:48:32.218] [LightClient] P2P                        peers=18
[INFO] [11-25|10:49:20.146] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:49:32.217] [LightClient] P2P                        peers=19
[INFO] [11-25|10:49:56.703] [5/16 Bodies] Writing block bodies       block_num=15880211 remaining=165950 alloc=4.1GB sys=6.1GB
[INFO] [11-25|10:49:56.739] [5/16 Bodies] Downloading block bodies   block_num=15880211 delivery/sec=7.0MB wasted/sec=0B remaining=165949 delivered=62513 alloc=4.1GB sys=6.1GB
[INFO] [11-25|10:50:32.218] [LightClient] P2P                        peers=19
[INFO] [11-25|10:51:20.145] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:51:32.218] [LightClient] P2P                        peers=20
[INFO] [11-25|10:52:32.217] [LightClient] P2P                        peers=19
[INFO] [11-25|10:53:20.145] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:53:32.218] [LightClient] P2P                        peers=19
[INFO] [11-25|10:54:32.217] [LightClient] P2P                        peers=18
[INFO] [11-25|10:55:20.145] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:55:23.558] [5/16 Bodies] Writing block bodies       block_num=15880789 remaining=165372 alloc=2.7GB sys=6.1GB
[INFO] [11-25|10:55:23.558] [5/16 Bodies] Downloading block bodies   block_num=15880789 delivery/sec=5.7MB wasted/sec=0B remaining=165949 delivered=64082 alloc=2.7GB sys=6.1GB
[INFO] [11-25|10:55:32.217] [LightClient] P2P                        peers=18
[INFO] [11-25|10:56:32.218] [LightClient] P2P                        peers=18
[INFO] [11-25|10:57:20.145] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|10:57:32.218] [LightClient] P2P                        peers=18
[INFO] [11-25|10:58:32.218] [LightClient] P2P                        peers=19
[INFO] [11-25|10:59:20.146] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|10:59:32.218] [LightClient] P2P                        peers=18
[INFO] [11-25|11:00:32.217] [LightClient] P2P                        peers=17
[INFO] [11-25|11:01:10.902] [5/16 Bodies] Writing block bodies       block_num=15881321 remaining=164840 alloc=3.4GB sys=6.1GB
[INFO] [11-25|11:01:10.902] [5/16 Bodies] Downloading block bodies   block_num=15881321 delivery/sec=4.9MB wasted/sec=0B remaining=165371 delivered=65415 alloc=3.4GB sys=6.1GB
[INFO] [11-25|11:01:20.145] [p2p] GoodPeers                          eth66=33 eth67=33
[INFO] [11-25|11:01:32.217] [LightClient] P2P                        peers=18
[INFO] [11-25|11:02:32.218] [LightClient] P2P                        peers=17

[INFO] [11-25|11:03:20.145] [p2p] GoodPeers                          eth66=33 eth67=32
[INFO] [11-25|11:03:32.217] [LightClient] P2P                        peers=17



[INFO] [11-25|11:04:32.218] [LightClient] P2P                        peers=17
[INFO] [11-25|11:05:20.145] [p2p] GoodPeers                          eth66=33 eth67=31

[INFO] [11-25|11:05:32.218] [LightClient] P2P                        peers=17
[INFO] [11-25|11:06:32.217] [LightClient] P2P                        peers=17
[INFO] [11-25|11:07:15.825] [5/16 Bodies] Writing block bodies       block_num=15882109 remaining=164052 alloc=2.8GB sys=6.1GB
[INFO] [11-25|11:07:15.864] [5/16 Bodies] Downloading block bodies   block_num=15882109 delivery/sec=4.3MB wasted/sec=0B remaining=164051 delivered=66583 alloc=2.8GB sys=6.1GB
[INFO] [11-25|11:07:20.145] [p2p] GoodPeers                          eth66=33 eth67=31
[INFO] [11-25|11:07:32.217] [LightClient] P2P                        peers=17
[INFO] [11-25|11:08:32.217] [LightClient] P2P                        peers=17
```

My guess: we stuck in `select` (which printing logs) without `default`

**Comment by AskAlexSharov** [comment] 2022-11-25 11:44
In list of goroutines - when it doesn't print logs - i see `body_algos.go:addBodyToBucket`
```

1 @ 0x427fbc 0x8d974c 0x8dba53 0x8db811 0xdccce5 0xdccce6 0xdc9b28 0x12cbd2a 0x12ca932 0x135046b 0x134f3a2 0x1339b2f 0x13a57ad 0x13a46c7 0x1b253eb 0x1b24a25 0x492861
#	0x8d974b	github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_put2+0x4b				_cgo_gotypes.go:1087
#	0x8dba52	github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put.func1+0xb2					github.com/torquem-ch/mdbx-go@v0.26.3-0.20221124080648-cfaf889d3e82/mdbx/cursor.go:239
#	0x8db810	github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put+0x90						github.com/torquem-ch/mdbx-go@v0.26.3-0.20221124080648-cfaf889d3e82/mdbx/cursor.go:239
#	0xdccce4	github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).put+0xa4				github.com/ledgerwatch/erigon-lib@v0.0.0-20221124111947-c832e7208620/kv/mdbx/kv_mdbx.go:1161
#	0xdccce5	github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).Put+0xa5				github.com/ledgerwatch/erigon-lib@v0.0.0-20221124111947-c832e7208620/kv/mdbx/kv_mdbx.go:1434
#	0xdc9b27	github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).Put+0x87					github.com/ledgerwatch/erigon-lib@v0.0.0-20221124111947-c832e7208620/kv/mdbx/kv_mdbx.go:959
#	0x12cbd29	github.com/ledgerwatch/erigon/turbo/stages/bodydownload.(*BodyDownload).addBodyToBucket+0x3a9	github.com/ledgerwatch/erigon/turbo/stages/bodydownload/body_algos.go:442
#	0x12ca931	github.com/ledgerwatch/erigon/turbo/stages/bodydownload.(*BodyDownload).GetDeliveries+0x851	github.com/ledgerwatch/erigon/turbo/stages/bodydownload/body_algos.go:330
#	0x135046a	github.com/ledgerwatch/erigon/eth/stagedsync.BodiesForward.func2+0xc0a				github.com/ledgerwatch/erigon/eth/stagedsync/stage_bodies.go:223
#	0x134f3a1	github.com/ledgerwatch/erigon/eth/stagedsync.BodiesForward+0xce1				github.com/ledgerwatch/erigon/eth/stagedsync/stage_bodies.go:339
#	0x1339b2e	github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func13+0x8e				github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:75
#	0x13a57ac	github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage+0x16c				github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:345
#	0x13a46c6	github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run+0x286					github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:255
#	0x1b253ea	github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep+0x4ea					github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:178
#	0x1b24a24	github.com/ledgerwatch/erigon/turbo/stages.StageLoop+0x184					github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:94
```
My guess: maybe we re-write all bodies all the time (aka. didn't cleanup some in-memory buffer after flush to db).

**Comment by hexoscott** [comment] 2022-11-28 09:26
Good shout on the missing default in a select, will take a look

**Comment by hexoscott** [comment] 2022-11-30 14:36
I've had a little look at this again.  Adding bodies to the bucket is done when we get a delivery from sentry, so the memory there will be getting cleared as it's a new delivery every time (we'd still have the leak if this weren't so).  But we could be receiving a lot of bodies at once which is more than feasible with a lot of peers, and the code to flush them to the db just takes a long time as it's encoding them to RLP to do so, if we got a few thousand bodies in at once that could take some considerable time.  The writing to the bucket happens before we log out the downloading message so that would definitely explain why this isn't happening every 30 seconds.

Question is, how do we deal with this?  The bucket solved the memory issue as previously we were holding huge amounts of bodies in RAM, no they're on disk.  Do we hold a certain amount of bodies in RAM closer to the tip of where we're processing, maybe allow say 1000 bodies there and ones beyond that get written to the bucket?

**Comment by AskAlexSharov** [comment] 2022-11-30 15:06
1. any proofs that writing to bucket is slow? how slow? do we do "random-write" or "append"?
2. we can print logs every 30 sec, if it's really slow
3. we can flush to db more often - just to utilize network better?

**Comment by hexoscott** [comment] 2022-11-30 15:33
1. just a hunch if a lot of bodies come in at once it could cause some delay, how much we'd need to put some logs in which I'll do locally now.  We're using `tx.Put` which would be random write, would append give us some performance benefit on write?
2. log printing happens after all handling of incoming body messages and body writing has occurred so we'd need that off in it's own routine to keep logging consistently.
3. in theory we flush to the db every second (every run of the Bodies forwards loop) + processing time for requesting more bodies + writing bodies.  If we get a steady stream of bodies in they will be processed quite quickly, but large chunks of them arriving at once is what I think is causing these delays.  Some logging for point 1 should help identify if this is the cause.

**Comment by AskAlexSharov** [comment] 2022-11-30 16:58
1. I mean - is it totally random keys, or they are “almost” sorted? If sorted - then Put is fine.
2. No, we always printing logs in long loops - by non-blocking select with ticker

**Comment by hexoscott** [comment] 2023-02-01 11:24
With the recent work done by @AlexeyAkhunov around stage bodies to remove the need for a bucket in favour of a cache, and more aggressive pruning of peers, I'm going to close this one down.  Can re-open if we see the same pattern still.

**Closed by hexoscott** 2023-02-01 11:24 UTC
Labels: gateway
