### ISSUE TITLE
Dencun block number issue

### ISSUE THREAD

**Issue by antisaa** [ledgerwatch/erigon#9707] opened 2024-03-13 16:44 UTC
#### System information

Erigon version: `erigon:v2.58.1`

OS & Version: `Linux`

Commit hash:  201964581f94fa4099220fbb100406bcf02d1b4d

Chain/Network: Ethereum

#### Expected behaviour
I expect that block data is returned properly when quering `eth_getBlockByNumber` for block number 19426589, which is the block number of Dencun upgrade.

#### Actual behaviour
The block is not returned, rather I get error `rlp: element is larger than containing list`.

#### Steps to reproduce the behaviour
```curl -q -s -X POST -H 'Content-Type: application/json' --data '{"method":"eth_getBlockByNumber","params":["0x1286D1D",false],"id":1,"jsonrpc":"2.0"}' https://ethereum.santiment.net | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "rlp: element is larger than containing list"
  }
}```

**Comment by m-e-m-f-i-s-19** [comment] 2024-03-14 08:54
We are facing same issue. Some blocks can't be fetched with the response:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "rlp: element is larger than containing list"
  }
}
```

**Comment by andrpp** [comment] 2024-03-14 15:04
this issue is happening in `erigon:v2.58.2` as well

**Comment by somnathb1** [comment] 2024-03-18 19:43
Fixed in latest `devel` (can't reproduce)

**Closed by somnathb1** 2024-03-18 19:43 UTC
Labels: dencun

**Comment by ivan-genev** [comment] 2024-03-19 14:15
Hi @somnathb1 
we have two nodes with similar configuration 
this are Linux/Docker environment with images thorax/erigon:v2.58.1 and thorax/erigon:devel 
devel image `git_branch=devel git_tag=v2.54.0-570-g076beeaa56-dirty git_commit=076beeaa567e27b1836123af9c7a71e10d5aeacf` 
same blocks are failing on bout of our nodes 
```curl -q -s -X POST -H 'Content-Type: application/json' --data '{"method":"eth_getBlockByNumber","params":["0x1286D1D",false],"id":1,"jsonrpc":"2.0"}'  https://ethereum.internal.rpc```
some of the blocks are 
```
19426589 1286D1D
19426597 1286D25
19426599 1286D27
19426631 1286D47
19426636 1286D4C
19426648 1286D58
19426652 1286D5C
19426659 1286D63
19426665 1286D69
19426674 1286D72
19426678 1286D76
19426683 1286D7B
19426688 1286D80
19426696 1286D88
```
and everything started after Dencun `Block proposed on slot 8626178, epoch 269568` 
our config file is 
```
    datadir : "/data/erigon"
    chain : "mainnet"
    http : false
    torrent.download.rate: "80mb"
    private.api.addr : "0.0.0.0:9090"
    sentry.api.addr : "localhost:9091"
    txpool.disable: true
    pprof.addr : "0.0.0.0"
    pprof.port : "6061"
    authrpc.jwtsecret : "/data/erigon/jwt.hex"
    metrics: true
    metrics.addr: "0.0.0.0"
    metrics.port: "6060"```
    sentry txpool and rpcdaemon are started as separate process and we are using lighthouse for beacon node.
