### ISSUE TITLE
Panic while sync: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vladgovor77771** [ledgerwatch/erigon#4496] opened 2022-06-19 14:54 UTC
#### System information

Erigon version: `erigon version 2022.99.99-dev-c2518ad6`.

OS & Version: `Linux container-erigon-cc55f474f-98f76 5.4.0-90-generic #101-Ubuntu SMP`.
Running in Kubernetes container. Delegated resources: 
```
        resources:
          requests:
            memory: "20Gi"
            cpu: "6000m"
          limits:
            memory: "40Gi"
            cpu: "12000m"
```
Running mainnet node with prune flags: `./build/bin/erigon --ws --http --prune=hrtc`.

Commit hash : `c2518ad6a336207e9b284e51a54b6256a31c8e1b`
Branch: `devel`

I've tried to sync 2 times. First time paniced after stage 9
![telegram-cloud-photo-size-2-5294305473547322196-y](https://user-images.githubusercontent.com/39651842/174487090-dc203fa9-8de3-405c-9a1e-77508f64dab1.jpg)
Second time paniced after execution. Backtrace below.

#### Backtrace

````
[backtrace]
INFO[06-19|14:40:55.471] [5/16 Senders] Recovery                  block_number=14892783
INFO[06-19|14:41:25.476] [5/16 Senders] Recovery                  block_number=14911127INFO[06-19|14:41:55.472] [5/16 Senders] Recovery                  block_number=14929147
INFO[06-19|14:42:00.732] [p2p] GoodPeers                          eth66=32
INFO[06-19|14:42:19.736] Flushed buffer file                      name=/root/.local/share/erigon/etl-temp/erigon-sortable-buf-2020627011 alloc=4.0GB sys=12.3GBINFO[06-19|14:42:25.471] [5/16 Senders] Recovery                  block_number=14947003
INFO[06-19|14:42:55.474] [5/16 Senders] Recovery                  block_number=14963935
INFO[06-19|14:43:25.474] [5/16 Senders] Recovery                  block_number=14980740
INFO[06-19|14:43:41.991] Flushed buffer file                      name=/root/.local/share/erigon/etl-temp/erigon-sortable-buf-50651188 alloc=4.5GB sys=12.3GB
INFO[06-19|14:43:50.792] [5/16 Senders] etl: temp files removed   total size=1.7GB
INFO[06-19|14:43:50.804] [5/16 Senders] DONE                      in=13m55.332491301s
INFO[06-19|14:43:50.804] [6/16 Execution] Blocks execution        from=5800595 to=14990504
WARN[06-19|14:43:50.845] [6/16 Execution] Execution failed        block=5800596 hash=0x6a028b6e239f2b8ecc4664822c796f34d2789d8d7acd630122414f106452df13 err="mismatched receipt headers for block 5800596"
INFO[06-19|14:43:50.845] UnwindTo                                 block=5800595 bad_block_hash=0x6a028b6e239f2b8ecc4664822c796f34d2789d8d7acd630122414f106452df13
INFO[06-19|14:43:50.845] [6/16 Execution] Completed on            block=5800595
INFO[06-19|14:43:58.963] Timings (slower than 50ms)               Headers=2m49.096s BlockHashes=1.045s Bodies=11m0.515s Senders=13m55.332s Unwind Headers=8.104s
INFO[06-19|14:43:58.963] [snapshots] Retire Blocks                range=14500k-15000k
INFO[06-19|14:43:58.963] [1/16 Headers] Waiting for headers...    from=5800595panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdc8989]
goroutine 472162 [running]:
github.com/ledgerwatch/erigon-lib/compress.(*Getter).nextPos(0xc1ae925c00?, 0x40?)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220617182456-945b0e9e0f61/compress/decompress.go:312 +0x29github.com/ledgerwatch/erigon-lib/compress.(*Getter).Next(0xc0100b5840, {0x0, 0x0, 0x0})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220617182456-945b0e9e0f61/compress/decompress.go:389 +0x59
github.com/ledgerwatch/erigon/turbo/snapshotsync.expectedTxsAmount({0xc05cbcfa40, 0x24}, 0xdd40a0, 0xe4e1c0)        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1367 +0x1e5
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs({0x1f346e8?, 0xc000f00340}, {0x7f603e6fe360?, 0xc0010040a0}, {0xc05cbcfa40, 0x45}, {0xc000693b30, 0x22}, 0xdd40a0, 0xe4e1c0, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1217 +0xbc5
github.com/ledgerwatch/erigon/turbo/snapshotsync.dumpBlocksRange({0x1f346e8, 0xc000f00340}, 0x65b705?, 0xc0000a2260?, {0xc000693b30, 0x22}, {0xc000693b60, 0x23}, {0x7f603e6fe360, 0xc0010040a0}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1049 +0x365
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpBlocks({0x1f346e8, 0xc000f00340}, 0x44844d?, 0xe4e1c0, 0x7a120, {0xc000693b30, 0x22}, {0xc000693b60, 0x23}, {0x7f603e6fe360, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1031 +0x165
github.com/ledgerwatch/erigon/turbo/snapshotsync.retireBlocks({0x1f346e8, 0xc000f00340}, 0xdd40a0, 0xe4e1c0, {0x1, 0x0, 0x0, 0x0}, {0xc000693b30, 0x22}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:978 +0x205
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:939
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:962 +0x1c8
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:952 +0xf1
````

**Comment by jdubpark** [comment] 2022-06-19 16:41
Same error for me as well, syncing for the first time.

**Screenshot**

<img width="850" alt="Screen Shot 2022-06-19 at 11 39 54 AM" src="https://user-images.githubusercontent.com/21009231/174491401-7ad98915-c2db-4674-b17d-6f7574f2c4e8.png">
<img width="850" alt="Screen Shot 2022-06-19 at 11 40 01 AM" src="https://user-images.githubusercontent.com/21009231/174491403-236b071f-7f02-4d0c-9e47-33a53dfd6cf0.png">

**Backtrace**
```
INFO[06-19|11:34:56.686] [snapshots] Retire Blocks                range=14500k-15000k
INFO[06-19|11:34:56.686] [1/16 Headers] Waiting for headers...    from=5800595
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdbf569]

goroutine 628409 [running]:
github.com/ledgerwatch/erigon-lib/compress.(*Getter).nextPos(0xc1f8d19b00?, 0x39?)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220617182456-945b0e9e0f61/compress/decompress.go:312 +0x29
github.com/ledgerwatch/erigon-lib/compress.(*Getter).Next(0xc117acd840, {0x0, 0x0, 0x0})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220617182456-945b0e9e0f61/compress/decompress.go:389 +0x59
github.com/ledgerwatch/erigon/turbo/snapshotsync.expectedTxsAmount({0xc1f8d19940, 0x1d}, 0xdd40a0, 0xe4e1c0)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1367 +0x1e5
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs({0x1f2fd88?, 0xc000f22380}, {0x7f375438ecd0?, 0xc0005b00a0}, {0
xc1f8d19940, 0x3e}, {0xc00004ba80, 0x1b}, 0xdd40a0, 0xe4e1c0, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1217 +0xbc5
github.com/ledgerwatch/erigon/turbo/snapshotsync.dumpBlocksRange({0x1f2fd88, 0xc000f22380}, 0x6522e5?, 0xc000146240?, {0
xc00004ba80, 0x1b}, {0xc00004baa0, 0x1c}, {0x7f375438ecd0, 0xc0005b00a0}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1049 +0x365
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpBlocks({0x1f2fd88, 0xc000f22380}, 0xc06b089578?, 0xe4e1c0, 0x7a120,
 {0xc00004ba80, 0x1b}, {0xc00004baa0, 0x1c}, {0x7f375438ecd0, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1031 +0x165
github.com/ledgerwatch/erigon/turbo/snapshotsync.retireBlocks({0x1f2fd88, 0xc000f22380}, 0xdd40a0, 0xe4e1c0, {0x1, 0x0,
0x0, 0x0}, {0xc00004ba80, 0x1b}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:978 +0x205
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:939
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:962 +0x1c8
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:952 +0xf1
```

**Comment by mtgnoah** [comment] 2022-06-19 17:59
I also got the same error on the same block so I'm wondering if something is odd about that exact block like something is null which usually isn't null. First time syncing too on Ubuntu. settings were `./build/bin/erigon --datadir=mainnet --torrent.download.rate=20mb --http`

**Comment by kaikash** [comment] 2022-06-19 18:45
Same for me. Looks like a bug?

**Comment by alysak6075** [comment] 2022-06-19 21:19
Same issue

**Comment by AskAlexSharov** [comment] 2022-06-20 02:45
workaround: —snap.stop

**Comment by mtgnoah** [comment] 2022-06-20 03:30
I think commit f838268 may have caused the issue because I migrated back to b06b4b4 and it works fine now. I believe their is an issue in block_snapshots.go in the way blocks are retired

**Comment by AlexeyAkhunov** [comment] 2022-06-20 05:51
This was a regression in 2022.06.04-alpha, fixed in `devel`

**Comment by AlexeyAkhunov** [comment] 2022-06-20 05:52
For now, I recommend downgrading to `2022.06.03` until the next release. Thank you for reporting

**Comment by jdubpark** [comment] 2022-06-21 07:47
Can confirm that version `2022.06.30` works. No error on block `5800596`

FYI, `git checkout tags/v2022.06.03 --force` (**WARNING: OVERWRITES**)

![Screen Shot 2022-06-21 at 2 44 28 AM](https://user-images.githubusercontent.com/21009231/174744730-dddcd7c7-fbd8-4434-bc31-50c69e95c636.png)

Thanks @AlexeyAkhunov for the quick response!

**Comment by mandrigin** [comment] 2022-06-30 15:19
closing this one because I assume it isn't the issue on the latest release (https://github.com/ledgerwatch/erigon/releases/tag/v2022.06.06). Please reopen if that is not true.

**Closed by mandrigin** 2022-06-30 15:19 UTC
