### ISSUE TITLE
eth_getTransactionReceipt returns null

### ISSUE THREAD

**Issue by vladmolkov** [ledgerwatch/erigon#2633] opened 2021-09-06 13:48 UTC
#### System information

Erigon version: `erigon version 2021.08.5-alpha`

OS & Version: `Ubuntu 20.04.3 LTS`

Commit hash : 

#### Expected behaviour
eth_getTransactionReceipt method returns the receipt of [certain transaction](https://goerli.etherscan.io/tx/0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f) how OE does it

#### Actual behaviour
eth_getTransactionReceipt method returns null

#### Steps to reproduce the behaviour
```
# run erigon and rpcdaemon
erigon --chain=goerli --maxpeers=30 --datadir=/data --private.api.addr=127.0.0.1:9090
rpcdaemon --datadir=/data --private.api.addr=127.0.0.1:9090 --http.addr=0.0.0.0 --http.port=8080 --http.api=eth,erigon,web3,net,debug,trace,txpool,shh,db --http.vhosts=*

# make request
curl --data '{"jsonrpc":"2.0","id":370925,"method":"eth_getTransactionReceipt","params":["0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f"]}' -H "Content-Type: application/json" -X POST localhost:8080
{"jsonrpc":"2.0","id":370925,"result":null}

# meanwhile OE  returns receipt
curl --data '{"jsonrpc":"2.0","id":370925,"method":"eth_getTransactionReceipt","params":["0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f"]}' -H "Content-Type: application/json" -X POST localhost:8080
{"jsonrpc":"2.0","result":{"blockHash":"0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67","blockNumber":"0x5320a6","contractAddress":null,"cumulativeGasUsed":"0x21bee","effectiveGasPrice":"0x12a05f200","from":"0x65b4a0f6d44dc63848def955493a10d0aaf9ffad","gasUsed":"0x15259","logs":[{"address":"0x5e6229f2d4d977d20a50219e521de6dd694d45cc","blockHash":"0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67","blockNumber":"0x5320a6","data":"0x4b1cc56c4a5aeabf4f6d1d81bfc7b90502f844a24693d5d11f53e24cebf21d66","logIndex":"0x1","removed":false,"topics":["0x9866f8ddfe70bb512b2f2b28b49d4017c43f7ba775f1a20c61c13eea8cdac111"],"transactionHash":"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f","transactionIndex":"0x1","transactionLogIndex":"0x0","type":"mined"},{"address":"0x5e6229f2d4d977d20a50219e521de6dd694d45cc","blockHash":"0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67","blockNumber":"0x5320a6","data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000022","logIndex":"0x2","removed":false,"topics":["0x4264ac208b5fde633ccdd42e0f12c3d6d443a4f3779bbf886925b94665b63a22","0x047291e251fbe8bbd4e0384552ec6bda047df3212e6166c7302e2f980ed0281c","0x0000000000000000000000004d6aa5fee627539a0eeaacae945bdd54c9bf959c"],"transactionHash":"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f","transactionIndex":"0x1","transactionLogIndex":"0x1","type":"mined"},{"address":"0x5e6229f2d4d977d20a50219e521de6dd694d45cc","blockHash":"0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67","blockNumber":"0x5320a6","data":"0x0078cda79a692abf5bdc015381b58190be3579d87a9eaf7fb6d23f4138dd75380000000000000000000000000000000000000000000000000000000000001723","logIndex":"0x3","removed":false,"topics":["0xe8012213bb931d3efa0a954cfb0d7b75f2a5e2358ba5f7d3edfb0154f6e7a568"],"transactionHash":"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f","transactionIndex":"0x1","transactionLogIndex":"0x2","type":"mined"}],"logsBloom":"0x00000000010000000000000000000000000010000000000000000000000000004000000000000000000000000000000800000000000000000080000000000040000000000000000000000000004000000000000000000000000010000000000000000010000000000000400000000000000000000000000000000000000000000000000000420000000000000000000000400000000000000000000000000000000000000000000008000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000200000000000000800000000000000020000000000000000000000000000000000000000000000","status":"0x1","to":"0x5e6229f2d4d977d20a50219e521de6dd694d45cc","transactionHash":"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f","transactionIndex":"0x1"},"id":370925}
```

#### Backtrace

````
[backtrace]
````

**Comment by mmgen** [comment] 2021-09-07 18:00
Are you certain the transaction was already mined when you made the first call?

eth_getTransactionReceipt returns null or zero if transaction is still pending, that's it's normal behavior.

**Comment by vladmolkov** [comment] 2021-09-08 08:24
Yes, transaction was mined in block 5447846 (0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67), currently latest block on my node is 5461190.
I can see txid in result of eth_getBlockByHash, but eth_getTransactionReceipt still returns null
```
# curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}' -H "Content-Type: application/json" -X POST localhost:8080 | jq -r '.result' | xargs printf "%d\n"
5461190
# curl -s -H 'content-type: application/json' --data-binary '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67", false],"id":1}' localhost:8080 | jq '.result | .transactions | .[] | select(. == "0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f")'
"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f"
# curl --data '{"jsonrpc":"2.0","id":370925,"method":"eth_getTransactionReceipt","params":["0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f"]}' -H "Content-Type: application/json" -X POST localhost:8080
{"jsonrpc":"2.0","id":370925,"result":null}
```

**Comment by gelfand** [comment] 2021-09-13 18:51
> Erigon version: `erigon version 2021.08.5-alpha`

Please update to the version from the devel branch.

```
◆ erigon ❯❯❯ curl --data '{"jsonrpc":"2.0","id":370925,"method":"eth_getTransactionReceipt","params":["0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f"]}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","id":370925,"result":{"blockHash":"0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67","blockNumber":"0x5320a6","contractAddress":null,"cumulativeGasUsed":"0x21bee","effectiveGasPrice":"0x12a05f200","from":"0x65b4a0f6d44dc63848def955493a10d0aaf9ffad","gasUsed":"0x15259","logs":[{"address":"0x5e6229f2d4d977d20a50219e521de6dd694d45cc","topics":["0x9866f8ddfe70bb512b2f2b28b49d4017c43f7ba775f1a20c61c13eea8cdac111"],"data":"0x4b1cc56c4a5aeabf4f6d1d81bfc7b90502f844a24693d5d11f53e24cebf21d66","blockNumber":"0x5320a6","transactionHash":"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f","transactionIndex":"0x1","blockHash":"0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67","logIndex":"0x1","removed":false},{"address":"0x5e6229f2d4d977d20a50219e521de6dd694d45cc","topics":["0x4264ac208b5fde633ccdd42e0f12c3d6d443a4f3779bbf886925b94665b63a22","0x047291e251fbe8bbd4e0384552ec6bda047df3212e6166c7302e2f980ed0281c","0x0000000000000000000000004d6aa5fee627539a0eeaacae945bdd54c9bf959c"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000022","blockNumber":"0x5320a6","transactionHash":"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f","transactionIndex":"0x1","blockHash":"0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67","logIndex":"0x2","removed":false},{"address":"0x5e6229f2d4d977d20a50219e521de6dd694d45cc","topics":["0xe8012213bb931d3efa0a954cfb0d7b75f2a5e2358ba5f7d3edfb0154f6e7a568"],"data":"0x0078cda79a692abf5bdc015381b58190be3579d87a9eaf7fb6d23f4138dd75380000000000000000000000000000000000000000000000000000000000001723","blockNumber":"0x5320a6","transactionHash":"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f","transactionIndex":"0x1","blockHash":"0xdedd0238eee2ad017bfb6b617ed126a6c08467d2859fd360bbc665174846da67","logIndex":"0x3","removed":false}],"logsBloom":"0x00000000010000000000000000000000000010000000000000000000000000004000000000000000000000000000000800000000000000000080000000000040000000000000000000000000004000000000000000000000000010000000000000000010000000000000400000000000000000000000000000000000000000000000000000420000000000000000000000400000000000000000000000000000000000000000000008000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000200000000000000800000000000000020000000000000000000000000000000000000000000000","status":"0x1","to":"0x5e6229f2d4d977d20a50219e521de6dd694d45cc","transactionHash":"0x8a6a190f828d65a1b713bdc51b6a4511c943f048522005c947711c7b6de3148f","transactionIndex":"0x1","type":"0x0"}}```

**Comment by vladmolkov** [comment] 2021-09-14 09:35
Still returns null using: `Build info                               git_branch=devel git_tag=v2021.09.02 git_commit=ced5965ef798e1975064123377289b7004f89567`
Maybe I should deploy new erigon instance and make it fully synced with "fresh" erigon version

**Comment by AskAlexSharov** [comment] 2021-09-14 12:02
@vladmolkov if it’s easy for you

**Comment by vladmolkov** [comment] 2021-09-14 13:23
I've started syncing new goerli instance builded from devel branch (ced5965e), soon i'll see how it works on new instance, but i'm worried about situation on my current instance, could it be data inconsistency or something like that?

**Comment by AskAlexSharov** [comment] 2021-09-14 13:40
hard to say without reproduce. it can return null in many cases - for example if block header missed, etc...

**Comment by vladmolkov** [comment] 2021-09-16 08:55
Ok, it works fine on new goerli instance, but my original issue look like serious problem related to data inconsistency, i mean it's definitely not expected behavior when erigon node keeps working with inconsistent database.

**Comment by AskAlexSharov** [comment] 2021-09-16 09:30
maybe some already fixed bug. 

you can investigate it if you like: collect list of all versions of erigon you used with that db, go `cmd/rpcdaemon/commands/eth_receipts.go:GetTransactionReceipt` and check what exactly piece of data missed - there are ReadTxLookupEntry and ReadBlockByNumberWithSenders which can return nil, also ReadBlockByNumberWithSenders internally has couple reasons why nil can be returned. 

We can't return exact reason by API, because we must maintain compatibility with Geth - and it does return nil if something missed, many existing software already rely on this behavior. For exampe: https://github.com/ledgerwatch/erigon/issues/1645

**Comment by vladmolkov** [comment] 2021-09-17 09:37
It looks like ReadTxLookupEntry returns nil instead of block number (also no errors returned).
I used `2021.08.01-alpha` and `2021.08.5-alpha` on that db before problem occurred, block number 5447846 was synced using `2021.08.5-alpha`.

**Comment by AskAlexSharov** [comment] 2021-09-18 05:40
If you get transactions from blocks around this block  - can you get receipt of them?

**Comment by vladmolkov** [comment] 2021-09-20 08:58
I've got something like this:
5447845 - all receipts received
5447846 - only one of five receipts received (0xd8f2836c015bec6dfd2cbe0f09601ffb54c752fced217adfa21ae08d9d6a47fb)
5447847 - all receipts received
5447848 - all receipts received

**Comment by AskAlexSharov** [comment] 2021-10-05 05:19
closing for now - because probably we will not debug further - easier to re-sync than figure out what combination of which versions and evens bring us to this point. If you will have more info or will have new cases after re-sync - feel free to reopen this issue or create new one.

**Closed by AskAlexSharov** 2021-10-05 05:19 UTC

**Comment by tholcman** [comment] 2021-12-15 11:54
Hi,

we are also getting `"result": null` on ethereum mainnet, on block number 13790465, which is now 2 days 22 hrs old. The block has 434 transactions, our geth nodes, as well as Infura and other public providers, returns proper receipt for all transactions while all our Erigon nodes return receipt only for 128 transactions (out of 434). `eth_getBlockByNumber` contains all transactions, block hash, everything else seems ok. but:

```
$ curl -X POST -H 'content-type:application/json' --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x7a3340105f9eeade204ef41e0933ecf7486f87ef1227fc17312f015543f5206c"],"id":1}' http://127.0.0.1:8545
{"jsonrpc":"2.0","id":1,"result":null}
```

We have 3 erigon nodes with this weird behavior.
We are running
```
$ erigon --version
erigon version 2021.12.1-beta
```
in docker `thorax/erigon:v2021.12.01`

and as we run `--gcmode archive`, sync from scratch would be painful.
