### ISSUE TITLE
No pending block found returning latest executed block

### ISSUE THREAD

**Issue by billyadelphia** [ledgerwatch/erigon#5325] opened 2022-09-10 03:36 UTC
Why I can't access pending block on erigon ? is there any parameter to enable accessing the pending block ?
it show these logs
version : erigon-2022.09.01
```
Sep 10 03:31:23 bsc3 erigon[21030]: [WARN] [09-10|03:31:23.982] no pending block found returning latest executed block
Sep 10 03:31:23 bsc3 erigon[21030]: [WARN] [09-10|03:31:23.982] no pending block found returning latest executed block
Sep 10 03:31:24 bsc3 erigon[21030]: [INFO] [09-10|03:31:24.056] [1/15 Headers] Processed                 highest inserted=21199497 age=0
Sep 10 03:31:24 bsc3 erigon[21030]: [WARN] [09-10|03:31:24.083] no pending block found returning latest executed block
Sep 10 03:31:24 bsc3 erigon[21030]: [WARN] [09-10|03:31:24.083] no pending block found returning latest executed block
Sep 10 03:31:24 bsc3 erigon[21030]: [INFO] [09-10|03:31:24.100] [6/15 Execution] Completed on            block=21199497
Sep 10 03:31:24 bsc3 erigon[21030]: [WARN] [09-10|03:31:24.183] no pending block found returning latest executed block
Sep 10 03:31:24 bsc3 erigon[21030]: [WARN] [09-10|03:31:24.184] no pending block found returning latest executed block
Sep 10 03:31:24 bsc3 erigon[21030]: [WARN] [09-10|03:31:24.284] no pending block found returning latest executed block
Sep 10 03:31:24 bsc3 erigon[21030]: [WARN] [09-10|03:31:24.284] no pending block found returning latest executed block
```

command :
```
/root/erigon/erigon-2022.09.01/build/bin/erigon --datadir=/root/data/erigon --torrent.download.rate=100mb --chain=bsc --prune=hrtc --db.pagesize=16k --http --ws -http.api=eth,erigon,web3,net,debug,trace,txpool
```

code
```js
import Web3 from "web3";
import testPending from "./testPending.js";

const web3 = new Web3("ws://localhost:8545");

const contract = new web3.eth.Contract(
  testPending,
  "0x08f35Ee2D4A29b5D84780c5B1631A6aC73c8325d"
);
const batman = async () => {
  const uu = await contract.methods.get().call({}, "pending");
  console.log("uu", uu);
  await sleep(100);
  batman().then().catch();
};
batman().then().catch();
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
```

**Comment by AskAlexSharov** [comment] 2022-09-10 04:00
probably need enable mining. something like --mine

**Comment by billyadelphia** [comment] 2022-09-10 04:10
@AskAlexSharov just tried it, but got this error, how to create a sigfile ?

```
Sep 10 04:07:22 bsc3 erigon[36553]: [EROR] [09-10|04:07:22.153] catch panic                              err="Flag --miner.sigfile is required in chain chain with --mine flag" stack="[main.go:30 panic.go:884 flags.go:998 flags.go:1468 node.go:94 main.go:57 app.go:526 app.go:286 main.go:35 proc.go:250 asm_amd64.s:1594]"
```

**Comment by billyadelphia** [comment] 2022-09-10 05:41
Added the `--mine` flag and `--miner.sigfile`, call the pending block again, now I have this error
```
Sep 10 05:38:00 bsc3 erigon[40456]: [WARN] [09-10|05:38:00.911] Served                                   method=eth_call reqid=1 t=72.596µs err="header not found for block 21201976, d9aa0ab4edec588ca1334442de36d5c2c21abd860f446d114635824de6ecdfb9"
```

command :
```
/root/erigon/erigon-2022.09.01/build/bin/erigon --datadir=/root/data/erigon --torrent.download.rate=100mb --chain=bsc --prune=hrtc --db.pagesize=16k --http --ws -http.api=eth,erigon,web3,net,debug,trace,txpool --mine --miner.sigfile=/root/erigon/private.key
```

**Comment by billyadelphia** [comment] 2022-11-11 03:41
@hexoscott I'm not mining or validating the block. Just wanted to access pending block on BSC. Because the bnb-client/bsc client can't access pending block too, they said they remove that capability because of performance issue.

Does the PRs will enable me to access the pending block ?

**Comment by hexoscott** [comment] 2022-11-28 08:01
Hi @billyadelphia, if you're not mining there won't be a pending block.  The PR will simply remove the log lines informing you that the pending block couldn't be found.

**Comment by hexoscott** [comment] 2022-11-28 08:04
Or a better way to put it is that in certain paths in the code there is a request for the pending block, if there isn't one then the code falls back to returning the latest block and logs out that a pending block couldn't be found.  The PR doesn't change the behaviour, just removes the log message as it hampers performance

**Comment by billyadelphia** [comment] 2022-11-28 22:15
@hexoscott just curious, why I can't get pending block unless do mining on BSC ? it is on purpose ? I'm able to access pending block on other network with other client, like on ethereum with geth or on polygon on bor.
I haven't tried running ethereum or polygon with erigon.

And can I modify some code to be able to access the pending block on BSC ?

**Comment by hexoscott** [comment] 2022-11-29 08:42
Ah ok, @billyadelphia, that might be my bad in that case then and some confusion around the pending block.  My understanding is that there isn't always a pending block available, at which point the code will fall back to the latest block instead.  You can see this in the function `_GetBlockNumber` in turbo/rpchelper//helper.go line 65.  There used to be a log line that let you know this had happened but it hampered performance for a lot of calls so was removed.

**Comment by Sengoku11** [comment] 2022-12-02 23:03
Is there a way to enable pending block in BSC? Since I'm not on the list of 21 validators, I'm not sure if I can enable mining on my node properly.

**Comment by hexoscott** [comment] 2023-02-23 09:18
Hi @billyadelphia, @Sengoku11.  I think I've possibly misunderstood your request here.  The "pending" block in erigon is always the block being mined, if you're not in a mining state there won't be one as they're not gossiped, in that case we return the latest executed block.  So we have 3 blocks that could be labelled as "pending":

1. the block being actively mined
2. the latest executed block
3. the latest block confirmed by a fork choice update
4. Blocks received via new payload that haven't yet been committed because we haven't received the fork choice update

The code path for eth_getBlock will return 2 if 1 isn't available in the list above.  I need to look into the code further to see if point 2 and 4 are the same or we hold some in memory for a short period.  Would it be number 4 that you're looking to see as the "pending" block?

**Comment by hexoscott** [comment] 2023-03-13 17:53
Going to close this thread down.  If the issue is still a problem please feel to re-open.

**Closed by hexoscott** 2023-03-13 17:53 UTC
Labels: gateway, status:in-progress
