### ISSUE TITLE
mdbx_env_open: MDBX_VERSION_MISMATCH

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#4810] opened 2022-07-24 10:24 UTC
#### System information

Erigon version: `git_branch=devel git_tag=v2021.10.03-1522-g6f53d1ef4-dirty`
OS & Version: Linux
Commit hash : 6f53d1ef4d71d467c9bc641ff5bf5c2228154bf2
Network: mainnet

When updating from b6440eea1e2d5c8eb36ab176e275e0b0c12cb99d to latest devel the following error occurs:

````
[INFO] Build info                               git_branch=devel git_tag=v2021.10.03-1522-g6f53d1ef4-dirty git_commit=6f53d1ef4d71d467c9bc641ff5bf5c2228154bf2
[INFO] Starting Erigon on Ethereum mainnet...
[INFO] Maximum peer count                       ETH=15 total=15
[INFO] torrent verbosity                        level=2
[INFO] Set global gas cap                       cap=50000000
[INFO] Opening Database                         label=chaindata path=/erigon/chaindata
mdbx_setup_lck:16495 lock region has os/format signature 0x3634d65f, expected 0x3634fb9f
[EROR] Erigon startup                           err="mdbx_env_open: MDBX_VERSION_MISMATCH: DB version mismatch libmdbx, label: chaindata, trace: [kv_mdbx.go:214 node.go:323 node.go:326 backend.go:157 node.go:121 node.go:112 main.go:41 app.go:526 app.go:286 main.go:28 proc.go:250 asm_amd64.s:1571]"
erigon.service: Deactivated successfully.
````

I didn't read in the release notes that a resync is required, so I am assuming it is a bug.

**Comment by veteransmod** [comment] 2022-07-24 13:39
https://direct.lc.chat/14345826/

**Comment by AskAlexSharov** [comment] 2022-07-25 00:50
What was previous erigon version?

**Comment by AskAlexSharov** [comment] 2022-07-25 00:53
1. Maybe you didn’t update rpcdaemon 
2. Maybe one more erigon working in background
3. Otherwise remove mdx.lck file

**Comment by flywukong** [comment] 2022-07-25 05:56
I have a nearly same error when starting rpcdaemon ,  using devel branch , only one erigon process on node
 
[EROR] [07-25|04:21:40.372] Could not connect to DB                  err="mdbx_env_open: MDBX_VERSION_MISMATCH: DB version mismatch libmdbx, label: chaindata, trace: [kv_mdbx.go:214 config.go:260 main.go:19 command.go:872 command.go:990 command.go:918 command.go:911 main.go:38 proc.go:250 asm_arm64.s:1263]"
~

**Comment by AskAlexSharov** [comment] 2022-07-25 06:53
can't reproduce. can switch forward and backward between this 2 commits - on linux and mac.

**Comment by AskAlexSharov** [comment] 2022-07-25 06:53
maybe show more logs

**Comment by geomad** [comment] 2022-07-25 10:18
**SOLVED:**
Turns out the error is occurring when after updating I was trying to restart erigon, while the old version of rpcdaemon was still running.
Shutting down both erigon and rpcdaemon, updating and then starting them solved the issue.

After starting up erigon I was having another issue:
`[EROR] Erigon startup                           err="clean tmp dir: /erigon/etl-temp, open /erigon/etl-temp: no such file or directory"`
Which was fixed by manually creating the folder in question.

**Comment by mandrigin** [comment] 2022-07-26 11:00
@geomad thanks! I am closing this issue. The one with the tmp dir is also solved on the very latest devel.

**Closed by mandrigin** 2022-07-26 11:00 UTC
