### ISSUE TITLE
Huge resident memory usage during normal operation

### ISSUE THREAD

**Issue by anonqoder** [ledgerwatch/erigon#4515] opened 2022-06-22 05:43 UTC
erigon version 2022.06.3-alpha-2a570ad5
Fedora Linux 35
32GB RAM

This is the report from 'top':

|  PID | RES |  RSan  |  SHR  | SWAP  |  %MEM  |   COMMAND                       
| ---- | ---- |  ----  |  ----  | ----  |  ----  |   ----          
| 617451 |  10.6g |   7.1g  |  3.5g  |  573712  |  34.1  |   home/eth/release/erigon --datadir=/home//erigon --prune=hrtc

We can see that ```RSan``` (Resident Anonymous) is at a whooping ```7.1 GB``` and ```3.5 GB``` is from shared memory mapped to files

The documentation imply the non shared memory should be kept at around 1GB

For comparison, Geth Mainnet uses 4GB of RSan (but no shared memory) and Erigon Goerli uses 1.8GB of RSan

I am trying to move away from geth to save on memory, but it seems Erigon is now drifting towards being more memory intensive?

**Comment by gavriilos** [comment] 2022-06-24 18:04
Feeling the same pain here. After reading the docs I got pretty sure I would be able to run Erigon in 8 GB of RAM. Unfortunately that's impossible. As of `2022.06.06-alpha`, even with (minor) tweaks such as `--state.cache 0`, it globs up all available memory and eventually gets killed by the OOM killer.

@AskAlexSharov please let us know once those memory optimization are implemented. Would love to give Erigon another go.

**Comment by KaiRo-at** [comment] 2022-06-29 12:39
FWIW, since about June 20, so that should be the update to 2022.06.05 or .06, our Goerli node looks a lot like it has a memory leak, consuming more and more memory the longer it runs, and it pretty much starts off with higher usage than the versions before.

**Comment by AskAlexSharov** [comment] 2022-06-29 14:21
@KaiRo-at we have 1 same report from BSC. Investigating. You can try to attach logs here, maybe it will helpful.

**Comment by mandrigin** [comment] 2022-06-30 15:13
@KaiRo-at can you try to run it with `--pprof` and then take a heap profile after your node suspiciously grew in RAM?

if you enable this flag then you can do `curl <node_address>:6060/debug/pprof/heap > heap.out` and then share this file with us here on in Discord so we can see the trace?

**Comment by KaiRo-at** [comment] 2022-07-04 12:23
> @KaiRo-at can you try to run it with `--pprof` and then take a heap profile after your node suspiciously grew in RAM?

I realized that this node had issues doing a snapshot merge due to not having enough disk space on the SSD. I did move the snapshots to the harddisk and symlinked it into the Erigon directory, which freed enough space to let the snapshot merge finish, and now the leak is gone as well - so it was connected to this failing snapshot merge.

**Comment by mandrigin** [comment] 2022-07-16 09:22
great! so I will close it for now. In case someone reproduces that on the latest build, please comment with the pprof result (see https://github.com/ledgerwatch/erigon/issues/4515#issuecomment-1171345508 on how to do so) and I will reopen it.

**Closed by mandrigin** 2022-07-16 09:22 UTC

**Comment by gavriilos** [comment] 2022-07-16 11:37
@mandrigin The original issue reported by @anonqoder is not the memory leak that @KaiRo-at experienced, but rather the huge amount of resident memory that Erigon uses now. As @anonqoder reported, Erigon is now using over 7 GB of resident memory, which is way over what is [reported in the documentation](https://github.com/ledgerwatch/erigon/blob/v2022.07.02/README.md#htop-shows-incorrect-memory-usage):

> Erigon uses ~4Gb of RAM during genesis sync and ~1Gb during normal work.

As such, this issue is still unresolved. I guess that the easiest way for you to deal with it now is just to update the documentation to reflect the current amount of resident memory usage.

**Comment by mandrigin** [comment] 2022-07-16 12:09
@gavriilos sure, I am not near my computer for the time being but if you want to make a contribution, updating the docs I will happily merge the PR.
