### ISSUE TITLE
Preindexed snapshots

### ISSUE THREAD

**Issue by mikolajsobolewski** [ledgerwatch/erigon#5736] opened 2022-10-13 09:22 UTC
# Rationale

I think this feature will make speed of node syncing so much. After downloading torrents snapshots of blocks, node make very slow and consumed a lot of memory indexation stage.

# Implementation

I think it's possible to store index snapshots nearby of blocks snapshot and download via torrents too.

**Comment by AskAlexSharov** [comment] 2022-10-14 02:05
Right now by design every node has different indices. It using random “seed” value. To prevent “unbalance index” attack vector.

**Comment by AskAlexSharov** [comment] 2022-10-14 02:14
FYI: can change `GOMAXPROCS` evn variable to reduce amount of parallel indexers (and RAM as a result)

**Comment by allada** [comment] 2022-10-15 17:18
You can also download a pre-indexed one here:
https://github.com/allada/bsc-archive-snapshot
or
https://github.com/allada/eth-archive-snapshot

You can just delete the mdbx file(s) after the sync is done and you'd have just the snapshots + indexes.

**Comment by revitteth** [comment] 2022-10-20 14:10
Looks like we can close this - if any more questions please ask :)

**Closed by revitteth** 2022-10-20 14:10 UTC
