### ISSUE TITLE
Wrong trie root of block 4651798

### ISSUE THREAD

**Issue by codesport** [ledgerwatch/erigon#3248] opened 2022-01-12 19:00 UTC
This error has unfortunately  replicated itself 9 times within the past 13 hours for the same block number:

`Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d`

Is there anyway to bypass or force a correct block hash for block **4651798**? 

Incidentally, it appears similar to [issue 2611](https://github.com/ledgerwatch/erigon/issues/2611) which I believe was fixed with an update in September 2021. 

### System information

Erigon version: v2022.01.01 **AND** v2021.12.03

OS & Version: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-94-generic x86_64)

Commit hashes : db7fa3d0ed0758fdca29efd337c85200a290becf **AND**  748abd39f68b44408555dc6eb6648999f6b5a7ad

### Expected behaviour
Block and hash should be processed correctly

### Actual behaviour
Whenever Erigon reaches block **4651798** is does a forced restart and unwinds all the transactions. 

This seems to be a continuous error loop because it's happened 9 times in the past 13 hours.

### Steps to reproduce the behaviour
**Use-case:** Deploying Erigon with Lighthouse for proof-of-stake on the Ethereum main net. 

This error occurred on a fresh install on new Ubuntu 20.04 server.  Below is how we configure and launch Erigon:

**/etc/systemd/system/eth1-erigon.service**

```
[Unit]
Description    = Erigon ETH1 Execution Client service
Wants            = network-online.target
After              = network-online.target 
Requires        = erigon-rpcdaemon.service

[Service]
Type            = simple
User            = $USER
ExecStart       = $HOME/erigon/build/bin/erigon --datadir /var/lib/erigon --chain mainnet --private.api.addr=localhost:9089 --metrics --pprof --prune htc --prune.r.before=11184524
Restart         = on-failure
RestartSec      = 3
KillSignal      = SIGINT
TimeoutStopSec  = 5

[Install]
WantedBy    = multi-user.target
```

### Backtrace
**Output from `journalctl -fu eth1-erigon --since=yesterday |grep 'Wrong trie root of block '`:**

```
Jan 12 02:35:44 codesport-server erigon[19863]: [EROR] [01-12|02:35:44.711] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d
Jan 12 03:09:38 codesport-server erigon[22609]: [EROR] [01-12|03:09:38.695] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d
Jan 12 03:44:39 codesport-server erigon[24519]: [EROR] [01-12|03:44:39.823] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d
Jan 12 09:14:09 codesport-server erigon[1785]: [EROR] [01-12|09:14:09.050] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d
Jan 12 11:08:39 codesport-server erigon[1207]: [EROR] [01-12|11:08:39.657] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d
Jan 12 12:25:08 codesport-server erigon[4287]: [EROR] [01-12|12:25:08.457] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d
Jan 12 13:25:49 codesport-server erigon[9025]: [EROR] [01-12|13:25:49.180] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d
Jan 12 14:24:40 codesport-server erigon[13543]: [EROR] [01-12|14:24:40.826] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d
Jan 12 15:10:56 codepsort-server erigon[16401]: [EROR] [01-12|15:10:56.180] [8/15 IntermediateHashes] Wrong trie root of block 4651798: df42b15198499f9415e7cf0938f315c11283f8b247448a649b0620b659a658e5, expected (from header): 8662298f761a4e7b0d5888e3d6ff9a02a82ac8121d1f0a3f51503ffea144c3f9. Block hash: c9cbd5858dc7f22d1be0617d12538a9af048cb0db7897b73c050962029511d1d


```

**Output of  `journalctl -fu eth1-erigon`:**

```
Jan 12 14:16:48 codesport-server erigon[13543]: [INFO] [01-12|14:16:48.006] [4/15 Senders] Recovery                  block_number=4720218
Jan 12 14:16:59 codesport-server erigon[13543]: [INFO] [01-12|14:16:59.612] [4/15 Senders] DONE                      in=2m41.606386757s
Jan 12 14:16:59 codesport-server erigon[13543]: [INFO] [01-12|14:16:59.612] [5/15 Execution] Blocks execution        from=4651798 to=4723220
Jan 12 14:16:59 codesport-server erigon[13543]: [EROR] [01-12|14:16:59.804] [5/15 Execution] Execution failed        block=4651799 hash=0xa70eb6b4e416fcd11521a40f483e95d15264b3a5b07761e4bfa4b19ccfebca5a error="could not apply tx 190 from block 4651799 [0x8eaa5de58cde898d39655e1caf971501709cb9a2ebd2950706d83e99c855848d]: gas limit reached"
Jan 12 14:16:59 codesport-server erigon[13543]: [INFO] [01-12|14:16:59.804] UnwindTo                                 block=4651798 bad_block_hash=0xa70eb6b4e416fcd11521a40f483e95d15264b3a5b07761e4bfa4b19ccfebca5a
Jan 12 14:16:59 codesport-server erigon[13543]: [INFO] [01-12|14:16:59.804] [5/15 Execution] Completed on            block=4651798
Jan 12 14:18:30 codesport-server erigon[13543]: [INFO] [01-12|14:18:30.800] [p2p] GoodPeers                          eth66=54
Jan 12 14:19:17 codesport-server erigon[13543]: [INFO] [01-12|14:19:17.850] [1/15 Headers] Unwind done               in=2m3.579128879s
Jan 12 14:19:17 codesport-server erigon[13543]: [INFO] [01-12|14:19:17.851] [7/15 HashState] Promoting plain state   from=2325899 to=4651798
Jan 12 14:19:17 codesport-server erigon[13543]: [INFO] [01-12|14:19:17.851] [7/15 HashState] Incremental promotion started from=2325899 to=4651798 codes=true csbucket=AccountChangeSet
Jan 12 14:19:47 codesport-server erigon[13543]: [INFO] [01-12|14:19:47.852] [7/15 HashState] ETL [1/2] Extracting    from=AccountChangeSet current key=00000000004662c0 alloc="1.5 GiB" sys="5.1 GiB"
Jan 12 14:20:17 codesport-server erigon[13543]: [INFO] [01-12|14:20:17.852] [7/15 HashState] ETL [1/2] Extracting    from=AccountChangeSet current key=000000000046916f alloc="1.7 GiB" sys="5.1 GiB"
```

**Comment by codesport** [comment] 2022-01-12 19:45
Closing this issue. After 8 attempts and 12 hours.  There correct hash for block 4651798  was found.

**Comment by AskAlexSharov** [comment] 2022-01-13 05:39
I see `from=2325899 to=4651798` Erigon doesn't work this way - it must jump from 0 to latest block in 1 hope during genesis sync. 
So: 
- Or you have bad internet and stage_bodies not able to download block bodies by timeout - and Erigon moves to another stages.
- Or we have bug in stage_bodies which by some reason can't utilize good internet connection (we have 1 report about slow stage_bodies).

**Comment by codesport** [comment] 2022-01-13 06:58
@AskAlexSharov appreciate  your feedback.

* Doubt it's internet. The box is connected to AT&T gigabyte fibre with automatic failover to ~500mbps cable internet as a backup. Consensus client hummed along without any issues. 

* The output of `journalctl -fu eth1-erigon` is just a 4 minute snapshot of logs after running 24 hours straight. And ~ 1 hour after giving  the error on its 8th pass at block 4651798. It reached block 4651798 at around 12 hours. 

Would us posting a longer log timeframe help any?

Totally understand your team is swamped, but if we can get an idea of the fix applied in issue 2611 https://github.com/ledgerwatch/erigon/issues/2611 we can try to do a pull request with a fix -- although we are not Go developers

**Comment by AskAlexSharov** [comment] 2022-01-13 08:19
You are now in beginning of sync. I advise you just remove Erigon folder, switch to v2021.12.03 and try again. While we investigating. Because we can reproduce the problem - so, don't need much debug from you now.

**Comment by codesport** [comment] 2022-01-13 16:15
> You are now in beginning of sync. I advise you just remove Erigon folder, switch to v2021.12.03 and try again. While we investigating. Because we can reproduce the problem - so, don't need much debug from you now.

Appreciate the update.

Will hold off on reverting as we first noticed the error while running v2021.12.03. 

After running v2021.12.03 for 17 hours, we upgraded to v2022.01.01 and error persisted over the next 7 to 8 hours.

**Comment by AskAlexSharov** [comment] 2022-05-27 04:43
optimistically closing this issue. if it's still a problem - feel free to re-open

**Closed by AskAlexSharov** 2022-05-27 04:43 UTC
