### ISSUE TITLE
SIGSEGV in LightClientOptimisticUpdate

### ISSUE THREAD

**Issue by whidrasl** [ledgerwatch/erigon#6910] opened 2023-02-20 12:36 UTC
erigon periodically crashes with the following error (after restarting it can work for some hours):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14b15fd]

goroutine 1037077 [running]:
github.com/ledgerwatch/erigon/cl/cltypes.(*LightClientOptimisticUpdate).EncodingSizeSSZ(0x0)
	github.com/ledgerwatch/erigon/cl/cltypes/lightclient.go:620 +0x1d
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/communication/ssz_snappy.EncodeAndWrite({0x7ff31d034ef0?, 0xc0566bcf00?}, {0x2c29728, 0x0}, {0xc05c822a2c, 0x1, 0x1})
	github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/communication/ssz_snappy/encoding.go:34 +0xae
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/handlers.(*ConsensusHandlers).lightClientOptimisticUpdateHandler(0xc03433f1a0, {0x2c4c890, 0xc0566bcf00})
	github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/handlers/lightclient.go:82 +0x19d
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0xc03b0f6820, 0x42}, {0x7ff31d034e80?, 0xc0566bcf00})
	github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:580 +0x76
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:421 +0x74f
```

reproducable in v2.38.1, v2.39.0 with Goerli network with commandline: `erigon --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --private.api.addr=0.0.0.0:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,erigon,web3,net,debug,trace,txpool --ws --torrent.download.rate=512mb --datadir=/home/erigon/.local/share/erigon --chain=goerli --torrent.port=31071 --nat=extip:<IPv4 address>`

not reproduced with Ethereum mainnet

i'm not sure, but there wasn't such error in v2.34 with same command line

**Comment by sslivkoff** [comment] 2023-02-20 19:15
Im experiencing the same issue on goerli on 2.38.1 and 2.39. happening during the download stage for me. restarting fixes it for a bit. but it fails at different points each time

also the amd-64 binary release of 2.39 fails instantaneously for me. I had to compile 2.39 from source to get it to run

on mainnet 2.38.1 is working fine for me. have not tried 2.39 on mainnet

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14cc9bd]

goroutine 2626950 [running]:
github.com/ledgerwatch/erigon/cl/cltypes.(*LightClientOptimisticUpdate).EncodingSizeSSZ(0x0)
        github.com/ledgerwatch/erigon/cl/cltypes/lightclient.go:620 +0x1d
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/communication/ssz_snappy.EncodeAndWrite({0x7fbe80577360?, 0xc0802abf80?}, {0x2c7b5e8, 0x0}, {0xc00216670c, 0x1, 0x1})
        github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/communication/ssz_snappy/encoding.go:34 +0xae
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/handlers.(*ConsensusHandlers).lightClientOptimisticUpdateHandler(0xc004a993e0, {0x2ca75b0, 0xc0802abf80})
        github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/handlers/lightclient.go:82 +0x19d
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0xc0803999a0, 0x42}, {0x7fbe805772f0?, 0xc0802abf80})
        github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:580 +0x76
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
        github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:421 +0x74f
```

**Comment by sundafa** [comment] 2023-02-21 01:58
The bsc node has the same error in version v2.39.0

**Comment by AskAlexSharov** [comment] 2023-02-22 01:27
"Is there perhaps a bad actor node running in goerli?" - it doesn't really matter - erigon must not die in any such case.

**Comment by AskAlexSharov** [comment] 2023-02-22 01:42
I added some sleep(3sec) before retries in devel as a hot-fix. Will need add some retry-with-backoff strategy later. And of course not die because of error from third-party server.

**Comment by AskAlexSharov** [comment] 2023-02-22 03:08
fixed by https://github.com/ledgerwatch/erigon/pull/6922

**Comment by saez0pub** [comment] 2023-02-23 07:57
I've seen the first occurence 2023-02-19T20:43:59.482Z and then:

Date|Occurences
-- | --
2023-02-19 | 2
2023-02-20 | 16
2023-02-21 | 6
2023-02-22 | 7
2023-02-23 | 7

**Comment by saez0pub** [comment] 2023-02-23 08:10
Until 2023-01-30 v2.36.1
From 2023-01-30 to 2023-02-20 v2.37.0
From 2023-02-20 to 2023-02-21 v2.39.0
From 2023-02-21 I downgraded then to v2.37.0

**Comment by J-A-M-E-5** [comment] 2023-02-23 17:00
Just throwing in a reference to this as this SIGSEGV seems to be root cause what happened here (corrupting my db): https://github.com/ledgerwatch/erigon/issues/6935

**Comment by Giulio2002** [comment] 2023-02-27 16:10
fixed by https://github.com/ledgerwatch/erigon/pull/6941

**Comment by Giulio2002** [comment] 2023-02-27 16:11
> Just throwing in a reference to this as this SIGSEGV seems to be root cause what happened here (corrupting my db): #6935
> 
> Thought I'd mention as this happened on MAINNET which others did not see.

quite unlikely, lightclient do not touch main erigon db

**Closed by Giulio2002** 2023-02-27 16:10 UTC
