### ISSUE TITLE
rpcdaemon crashing when built with go 1.17

### ISSUE THREAD

**Issue by mdben1247** [ledgerwatch/erigon#2598] opened 2021-08-30 15:12 UTC
#### System information

Erigon version: 2021.08.5-alpha

OS & Version: Linux

Commit hash : b1fef26767f2635da6816f0dc07acd3f3fa1e935

#### Steps to reproduce the behaviour
I suspect the crashes happen during the execution of a batch call, querying the chain state after a new block is received. I had two such crashes now, both happened in a few hours after upgrading to 2021.08.05. Previous version (2021.08.04) worked well.

EDIT: Erigon release version is irrelevant. Crashing occurs when rpcdaemon is compiled with go 1.17 (or 1.17.1). When compiled with go 1.16, rpcdaemon works well, without any issues.

#### Backtrace
[backtrace.txt](https://github.com/ledgerwatch/erigon/files/7077629/backtrace.txt)

**Comment by mdben1247** [comment] 2021-08-30 16:34
I downgraded back to v2021.08.04 and I am still having the same rpcdaemon crashes. Not sure why this started happening today after the upgrade. I've been running erigon for more than a week and haven't had these crashes.

**Comment by AskAlexSharov** [comment] 2021-08-31 04:48
What is your go version?

**Comment by AskAlexSharov** [comment] 2021-08-31 05:15
error says `bad use of unsafe.Pointer? try -d=checkptr`. can you build rpcdaemon this way: 
```
go build -gcflags=all=-d=checkptr -o ./build/bin/rpcdaemon ./cmd/rpcdaemon
```
and then run as you usually do and show how it goes

**Comment by AskAlexSharov** [comment] 2021-08-31 05:25
what cli flags you use to run rpcdaemon?

**Comment by mdben1247** [comment] 2021-08-31 15:50
> ```
> go build -gcflags=all=-d=checkptr -o ./build/bin/rpcdaemon ./cmd/rpcdaemon
> ```

Thanks for looking into it. I tried building rpcdaemon this way, here is the backtrace from recent crash.
[backtrace2.txt](https://github.com/ledgerwatch/erigon/files/7085189/backtrace2.txt)

I am on v2021.08.04 now. 

`go version `gives `go1.17 linux/amd64`

Flags: `--datadir=... --http.port=... --http.api=eth,web3,erigon,net,trace --ws`

**Comment by mdben1247** [comment] 2021-08-31 19:07
I noticed previously attached trace (backtrace2.txt) still says `bad use of unsafe.Pointer? try -d=checkptr`. 

I rebuilt the executable again. I am attaching trace from another crash. This one now seems to have more info.
[backtrace3.txt](https://github.com/ledgerwatch/erigon/files/7086255/backtrace3.txt)

**Comment by AskAlexSharov** [comment] 2021-09-01 06:48
“  Not sure why this started happening today after the upgrade” maybe you was on go 1.16.*

i will dive into backtrace3 today. Not clear yet.

**Comment by mdben1247** [comment] 2021-09-01 08:10
> “ Not sure why this started happening today after the upgrade” maybe you was on go 1.16.*

You may be on to something, I checked installation logs and  I was  on go 1.16 until recently. I'll try downgrading to 1.16 and see if that helps.

**Comment by AskAlexSharov** [comment] 2021-09-01 08:53
Would be great if you can add 2 more build flags and get one more logs (race detector may write to logs before crush) or trace: 
`GODEBUG=cgocheck=2 go build -race -gcflags=all=-d=checkptr -o ./build/bin/rpcdaemon ./cmd/rpcdaemon`
because I can't reproduce yet.

**Comment by AskAlexSharov** [comment] 2021-09-01 09:08
One (probably) non-related thing: I advise you go to 2021.08.05-alpha (because 08.04 has known problem when using --datadir option of rpcdaemon - there happening big performance regression - it start eating too much Disk - some people experienced 100x degradation). But unlikely it's reason of crush.

**Comment by AskAlexSharov** [comment] 2021-09-02 07:58
this is great outcome

**Comment by mdben1247** [comment] 2021-09-02 09:15
Glad to hear you found them useful. I missed one race, it seems distinct from the above two:
[race3.txt](https://github.com/ledgerwatch/erigon/files/7097668/race3.txt)

**Comment by AskAlexSharov** [comment] 2021-09-02 10:02
if added 2 fixes (for this 3 races): one is in new release v2021.09.01, but one i merged to devel after release.

**Comment by mdben1247** [comment] 2021-09-02 10:33
I'll pull devel and let it run for a while.

**Comment by mdben1247** [comment] 2021-09-03 06:22
> I'll pull devel and let it run for a while.

Unfortunately, that didn't help. It crashed three times since. I'll test downgrading go to 1.16 now. 

A quick description of the workload, maybe it helps finding the bug. There are several web-socket connections (about 5-6) to rpcdameon. One of these receives new block subscriptions. The other connections (after getting a new block) simultaneously each sends a batch of queries (reading chain state). I suspect crashing happens somewhere here.

**Comment by AskAlexSharov** [comment] 2021-09-03 10:31
@mdben1247 
Please try to add `-race` flag (alone it likely will not add much CPU load).

I found 1 change which may lead to dangling pointers (reason of crush): https://github.com/ledgerwatch/erigon/pull/2564/files 
Here is the revert: https://github.com/ledgerwatch/erigon/pull/2627

**Comment by mdben1247** [comment] 2021-09-03 11:13
> Please try to add `-race` flag (alone it likely will not add much CPU load).

I'll try that next. Just to be sure, build like this?
`go build -race -o ./build/bin/rpcdaemon ./cmd/rpcdaemon`

**Comment by AskAlexSharov** [comment] 2021-09-03 11:18
Yes

**Comment by mdben1247** [comment] 2021-09-06 08:09
rpcdaemon built with go 1.16 works flawlessly, no crashing at all.


Built with go 1.17 it crashes regularly. I am attaching new traces using `-race` flag, however there where no races detected.
[backtrace4.txt](https://github.com/ledgerwatch/erigon/files/7114319/backtrace4.txt)
[backtrace5.txt](https://github.com/ledgerwatch/erigon/files/7114320/backtrace5.txt)

**Comment by mdben1247** [comment] 2021-09-07 10:21
Not sure how helpful those traces are. What has me a bit confused is there are `(bad use of unsafe.Pointer? try -d=checkptr)`suggestions in the traces, but `-race` build flag is supposed to imply `-d=checkptr` according to go [docs](https://golang.org/doc/go1.14). 

Any ideas on what else I can try to do to collect more data about the issue?

**Comment by AskAlexSharov** [comment] 2021-09-07 10:36
Maybe you can build old RPCDaemon? Let's say v2021.07.05 with go 1.17 and see if problem is still exists?

**Comment by mdben1247** [comment] 2021-09-07 10:54
> Maybe you can build old RPCDaemon? Let's say v2021.07.05 with go 1.17 and see if problem is still exists?

Hm... having trouble running this old version, I think database directory changed.

**Comment by mdben1247** [comment] 2021-09-07 16:43
> Maybe you can build old RPCDaemon? Let's say v2021.07.05 with go 1.17 and see if problem is still exists?

I tried that, but couldn't make it work, this old version is missing some functionality that was added later (like batch ordering) and is critical to running the whole thing.

I also tried building `devel` with
`GODEBUG=cgocheck=2 go build -gcflags=all=-d=checkptr -o ./build/bin/rpcdaemon ./cmd/rpcdaemon`
without `-race` flag (then it runs reasonably well) and here is a backtrace of a crash, but not sure if there is any new info here.
[backtrace7.txt](https://github.com/ledgerwatch/erigon/files/7123112/backtrace7.txt)

**Comment by AskAlexSharov** [comment] 2021-09-08 05:37
Ok. Thank you for helping. 

Maybe it's not related to "race condition", maybe it's "wrong unsafe usage". 
Let's first understand - if it's related to "unsafe usage related to database" (because our db is written in C).
Here is the branch: `copy_db_val`

**Comment by mdben1247** [comment] 2021-09-08 08:02
> Here is the branch: `copy_db_val`

This one is interesting, when it crashed it didn't say `bad use of unsafe.Pointer? try -d=checkptr`, but something else:
[backtrace8.txt](https://github.com/ledgerwatch/erigon/files/7127056/backtrace8.txt)

**Comment by AskAlexSharov** [comment] 2021-09-10 04:03
@mdben1247 hi. there is golang 1.17.1 released. Please try.

**Comment by mdben1247** [comment] 2021-09-16 10:21
> hi. there is golang 1.17.1 released. Please try.

Still crashing.

**Comment by AskAlexSharov** [comment] 2021-09-16 13:20
No other people reported this issue. Maybe something specific for your server?

**Comment by mdben1247** [comment] 2021-09-16 14:17
> No other people reported this issue. Maybe something specific for your server?

I'd say it's very unlikely. The server hardware has proven rock solid for past year or more, running under constant load 24/7, previously openethereum, now erigon (which also runs just awesomely on go 1.16). The more likely reason is we are running quite a workload, I suspect most people's erigon/rpcdaemon instances don't come near that stress level. That includes tx tracing, constantly querying various states, using batches, multiple ws connections etc.

**Comment by AskAlexSharov** [comment] 2021-09-17 03:48
ah, yes, we clearly know that on 1.16 you have no problem

**Comment by mandrigin** [comment] 2021-12-08 18:45
@mdben1247 if it still crashes on the latest go (1.17.4), please reopen and include the exact batch request that you have so we can try to reproduce it.

**Closed by mandrigin** 2021-12-08 18:45 UTC
