### ISSUE TITLE
Can't read old blocks using standalone rpcdaemon anymore on v2022.08.01

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#5069] opened 2022-08-15 22:03 UTC
Try to read an old block (which was moved to snapshots) using standalone rpcdaemon:

```
curl localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params": ["0xE4E9A2", false],"id":1}'
```

The following command used to work on v2022.07.04, but it is not working anymore on v2022.08.01.

Note: that is for running rpcdaemon without an active erigon node, i.e., rpcdaemon + datadir only, which is useful when you just want to query historical data adhoc without having to start full sync process.

Running standalone erigon (with embedded rpcdaemon), or erigon + rpcdaemon works. The regression seems to be related just to rpcdaemon without an active erigon node. Querying recent blocks (which were not moved to snapshots) works.

I was able to track down the regression to `api._blockReader.BlockWithSenders` call, apparently it is not looking for blocks in snapshots anymore in v2022.08.01.

**Comment by AskAlexSharov** [comment] 2022-08-16 01:30
can't reproduce
1. did you delete snapshots recently?
2. try branch `dbg_no_blocks2` it will print much debug lines when call eth_getBlockByNumber

**Comment by wmitsuda** [comment] 2022-08-16 03:39
1 - no, never deleted snapshots
2 - calling:

```
curl localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params": ["0xE4E9A2", false],"id":1}'
{"jsonrpc":"2.0","id":1,"result":null}
```

logs this:

```
INFO[08-16|00:33:02.376] HTTP endpoint opened                     url=localhost:8545 ws=true ws.compression=false grpc=false
WARN[08-16|00:33:15.400] dbg: BlockWithSenders. begin             sn.files()=[] blockHeight=15002018 back.sn.BlocksAvailable()=0 back.sn.SegmentsMax()=[] back.sn.IndicesMax()=0
[TRACE] [08-16|00:33:15.400] Served                                   conn=127.0.0.1:50744 t=4.137856ms method=eth_getBlockByNumber reqid=1 params="[\"0xE4E9A2\", false]"
```

calling older block:

```
curl localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params": ["0xE9A2", false],"id":1}'
{"jsonrpc":"2.0","id":1,"result":null}
```

logs this:

```
WARN[08-16|00:36:07.286] dbg: BlockWithSenders. begin             sn.files()=[] blockHeight=59810 back.sn.BlocksAvailable()=0 back.sn.SegmentsMax()=[] back.sn.IndicesMax()=0
[TRACE] [08-16|00:36:07.286] Served                                   conn=127.0.0.1:50815 t=125.279µs method=eth_getBlockByNumber reqid=1 params="[\"0xE9A2\", false]"
```

calling with recent block:

```
curl localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params": ["0xE975A0", false],"id":1}'
```

returns data correctly and logs this:

```
WARN[08-16|00:37:08.234] dbg: BlockWithSenders. begin             sn.files()=[] blockHeight=15300000 back.sn.BlocksAvailable()=0 back.sn.SegmentsMax()=[] back.sn.IndicesMax()=0
[TRACE] [08-16|00:37:08.246] Served                                   conn=127.0.0.1:50842 t=16.102422ms method=eth_getBlockByNumber reqid=1 params="[\"0xE975A0\", false]"
```

rpcdaemon cli flags:

```
~/turbo-geth/build/bin/rpcdaemon --datadir /Volumes/new-erigon-alpha --http.api "eth,net,web3,erigon,debug,txpool,trace,ots" --ws --http.corsdomain "*" --http.port 8545 --verbosity=5
```

**Comment by wmitsuda** [comment] 2022-08-16 03:40
erigon process is down, just to be clear.

**Comment by AskAlexSharov** [comment] 2022-08-16 08:45
fixed by https://github.com/ledgerwatch/erigon/pull/5073

**Closed by AskAlexSharov** 2022-08-16 08:45 UTC

**Comment by wmitsuda** [comment] 2022-08-16 19:14
thanks!
