### ISSUE TITLE
Cannot shutdown

### ISSUE THREAD

**Issue by guzkodes** [ledgerwatch/erigon#5007] opened 2022-08-11 12:54 UTC
erigon version 2022.08.1-alpha-7dabdc32

stopping the system process hangs. Last print logs:

```
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.477] RPC server shutting down
Aug 11 13:51:46 erigon[2458600]: [WARN] [08-11|13:51:46.477] Failed to serve http endpoint            err="http: Server closed"
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.478] HTTP endpoint closed                     url=127.0.0.1:9555
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.478] Engine HTTP endpoint close               url=localhost:9552
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.606] Timings (slower than 50ms)               Headers=3h30m21.926s Prune Senders=119ms
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.606] Tables                                   PlainState=10.7GB AccountChangeSet=141.7MB StorageChangeSet=656.2MB BlockTransaction=30.1GB TransactionLog=28.3GB FreeList=4.0KB ReclaimableSpace=4.0MB
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.611] [snapshots] Retire Blocks                range=7100k-7200k
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.680] Commit cycle                             in=74.632367ms
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.688] RPC Daemon notified of new headers       from=7382818 to=7382819 header sending=38.49µs log sending=577ns
Aug 11 13:51:46 erigon[2458600]: [INFO] [08-11|13:51:46.688] [1/16 Headers] Waiting for Beacon Chain...
```

Need to manually kill it

**Comment by revittm** [comment] 2022-08-12 08:43
I saw this issue yesterday too, will investigate.

**Comment by revitteth** [comment] 2022-09-01 10:46
Possibly related: https://github.com/ledgerwatch/erigon/issues/5094

**Comment by nanevardanyan** [comment] 2022-09-03 06:30
I am no longer able to reproduce this issue in the latest versions. It was probably fixed by https://github.com/ledgerwatch/erigon/pull/5194 . 
@guzkodes are you still having the issue?

**Comment by guzkodes** [comment] 2022-09-03 06:34
It started to manifest after the merge on Göerli, and it still happens. On mainnet it works fine.

**Comment by revitteth** [comment] 2022-09-05 07:50
@guzkodes is that still with version `2022.08.1-alpha-7dabdc32` or latest devel?

**Comment by guzkodes** [comment] 2022-09-05 07:52
yes

**Comment by revitteth** [comment] 2022-09-05 07:53
@guzkodes I guess that is 'yes' to latest version?

**Comment by revitteth** [comment] 2022-09-06 15:51
Closing as merged to devel.

**Closed by revitteth** 2022-09-06 15:51 UTC
Labels: gateway, status:testing

**Comment by dancoombs** [comment] 2022-09-07 18:37
I am still seeing this issue in v2022.09.01, which it looks like https://github.com/ledgerwatch/erigon/pull/5194 is included in.

**Comment by revitteth** [comment] 2022-09-07 23:56
> I am still seeing this issue in v2022.09.01, which it looks like #5194 is included in.

@dancoombs the fix is here:
https://github.com/ledgerwatch/erigon/pull/5286
